// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "gooey/control/v1/control.proto" (package "gooey.control.v1", syntax proto3)
// tslint:disable
//
// ControlService — the unary control plane.
//
// Every RPC here is one request, one settled answer: the server
// marshals the call onto the app's UI goroutine, waits for the settle
// barrier (the frame the call's Sets asked for has been composed), and
// only then answers. Reading the screen immediately after invoking a
// command therefore sees the new pixels — the same guarantee the MCP
// bridge gives today, promoted to the contract.
//
// Errors are gRPC status codes, not payload fields:
//   NOT_FOUND            — no such name in the binding context / tree
//   INVALID_ARGUMENT     — type mismatch (message names both types),
//                          bad markup, bad gesture, bad registration
//   FAILED_PRECONDITION  — no markup context, no live composition
//   DEADLINE_EXCEEDED    — the UI goroutine did not answer in time
//                          (the run loop is blocked or not running)
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StyleInfo } from "./types";
import { ControlSchema } from "./types";
import { PropertyRegistration } from "./types";
import { PointerEvent } from "./types";
import { TypedValue } from "./types";
import { ValueInfo } from "./types";
import { TreeNode } from "./types";
/**
 * @generated from protobuf message gooey.control.v1.SnapshotTreeRequest
 */
export interface SnapshotTreeRequest {
    /**
     * Maximum depth to walk; 0 means the whole tree.
     *
     * @generated from protobuf field: int32 depth = 1
     */
    depth: number;
}
/**
 * @generated from protobuf message gooey.control.v1.SnapshotTreeResponse
 */
export interface SnapshotTreeResponse {
    /**
     * @generated from protobuf field: gooey.control.v1.TreeNode root = 1
     */
    root?: TreeNode;
}
/**
 * @generated from protobuf message gooey.control.v1.ScreenTextRequest
 */
export interface ScreenTextRequest {
    /**
     * Return the ANSI escape stream the terminal would receive instead
     * of plain text.
     *
     * @generated from protobuf field: bool styled = 1
     */
    styled: boolean;
}
/**
 * @generated from protobuf message gooey.control.v1.ScreenTextResponse
 */
export interface ScreenTextResponse {
    /**
     * One line per terminal row, trailing blanks trimmed (plain), or the
     * raw escape stream (styled).
     *
     * @generated from protobuf field: string text = 1
     */
    text: string;
}
/**
 * @generated from protobuf message gooey.control.v1.ListValuesRequest
 */
export interface ListValuesRequest {
}
/**
 * @generated from protobuf message gooey.control.v1.ListValuesResponse
 */
export interface ListValuesResponse {
    /**
     * @generated from protobuf field: repeated gooey.control.v1.ValueInfo values = 1
     */
    values: ValueInfo[];
    /**
     * The Name= identities in the current tree — what SetFocus takes.
     *
     * @generated from protobuf field: repeated string named = 2
     */
    named: string[];
}
/**
 * @generated from protobuf message gooey.control.v1.GetPropertyRequest
 */
export interface GetPropertyRequest {
    /**
     * Dotted path in the binding context, resolved exactly as a
     * {{.A.B}} binding resolves.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message gooey.control.v1.GetPropertyResponse
 */
export interface GetPropertyResponse {
    /**
     * @generated from protobuf field: gooey.control.v1.ValueInfo value = 1
     */
    value?: ValueInfo;
}
/**
 * @generated from protobuf message gooey.control.v1.SetPropertyRequest
 */
export interface SetPropertyRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.TypedValue value = 2
     */
    value?: TypedValue;
}
/**
 * @generated from protobuf message gooey.control.v1.SetPropertyResponse
 */
export interface SetPropertyResponse {
}
/**
 * @generated from protobuf message gooey.control.v1.InvokeCommandRequest
 */
export interface InvokeCommandRequest {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message gooey.control.v1.InvokeCommandResponse
 */
export interface InvokeCommandResponse {
}
/**
 * @generated from protobuf message gooey.control.v1.SendKeysRequest
 */
export interface SendKeysRequest {
    /**
     * Literal text, one key event per rune, typed before `gestures`.
     *
     * @generated from protobuf field: string text = 1
     */
    text: string;
    /**
     * Gestures in markup syntax: "tab", "enter", "ctrl+s", "shift+tab".
     *
     * @generated from protobuf field: repeated string gestures = 2
     */
    gestures: string[];
}
/**
 * @generated from protobuf message gooey.control.v1.SendKeysResponse
 */
export interface SendKeysResponse {
    /**
     * @generated from protobuf field: int32 sent = 1
     */
    sent: number;
    /**
     * Per-event: whether the tree consumed it, in send order.
     *
     * @generated from protobuf field: repeated bool consumed = 2
     */
    consumed: boolean[];
}
/**
 * @generated from protobuf message gooey.control.v1.SendPointerRequest
 */
export interface SendPointerRequest {
    /**
     * @generated from protobuf field: gooey.control.v1.PointerEvent event = 1
     */
    event?: PointerEvent;
}
/**
 * @generated from protobuf message gooey.control.v1.SendPointerResponse
 */
export interface SendPointerResponse {
    /**
     * @generated from protobuf field: bool consumed = 1
     */
    consumed: boolean;
}
/**
 * @generated from protobuf message gooey.control.v1.SetFocusRequest
 */
export interface SetFocusRequest {
    /**
     * The element's Name= identity. The element must be a focus stop.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
}
/**
 * @generated from protobuf message gooey.control.v1.SetFocusResponse
 */
export interface SetFocusResponse {
}
/**
 * @generated from protobuf message gooey.control.v1.SwapMarkupRequest
 */
export interface SwapMarkupRequest {
    /**
     * Complete markup source, rooted at <Gooey> with exactly one child.
     *
     * @generated from protobuf field: string source = 1
     */
    source: string;
    /**
     * Properties to register into the binding context before the build,
     * so the new page may bind names the app never pre-registered
     * (issue #89). Rolled back if the build fails.
     *
     * @generated from protobuf field: repeated gooey.control.v1.PropertyRegistration register = 2
     */
    register: PropertyRegistration[];
}
/**
 * @generated from protobuf message gooey.control.v1.SwapMarkupResponse
 */
export interface SwapMarkupResponse {
    /**
     * The Name= identities of the new tree.
     *
     * @generated from protobuf field: repeated string named = 1
     */
    named: string[];
}
/**
 * @generated from protobuf message gooey.control.v1.RegisterPropertiesRequest
 */
export interface RegisterPropertiesRequest {
    /**
     * @generated from protobuf field: repeated gooey.control.v1.PropertyRegistration properties = 1
     */
    properties: PropertyRegistration[];
}
/**
 * @generated from protobuf message gooey.control.v1.RegisterPropertiesResponse
 */
export interface RegisterPropertiesResponse {
}
/**
 * @generated from protobuf message gooey.control.v1.UnregisterNamesRequest
 */
export interface UnregisterNamesRequest {
    /**
     * Dotted names to remove, e.g. "Result" or "Activity.Sparkle.Out".
     *
     * @generated from protobuf field: repeated string names = 1
     */
    names: string[];
}
/**
 * @generated from protobuf message gooey.control.v1.UnregisterNamesResponse
 */
export interface UnregisterNamesResponse {
}
/**
 * @generated from protobuf message gooey.control.v1.GetDeclaredSchemaRequest
 */
export interface GetDeclaredSchemaRequest {
    /**
     * Markup source to inspect. Empty asks for the declaration block of
     * the document the running page was built from, when the server
     * knows it.
     *
     * @generated from protobuf field: string source = 1
     */
    source: string;
}
/**
 * @generated from protobuf message gooey.control.v1.GetDeclaredSchemaResponse
 */
export interface GetDeclaredSchemaResponse {
    /**
     * @generated from protobuf field: gooey.control.v1.ControlSchema schema = 1
     */
    schema?: ControlSchema;
}
/**
 * @generated from protobuf message gooey.control.v1.PatchMarkupRequest
 */
export interface PatchMarkupRequest {
    /**
     * The Name= identity of the element to replace.
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * Markup for the replacement subtree, rooted at <Gooey> with exactly
     * one child carrying the same Name.
     *
     * @generated from protobuf field: string source = 2
     */
    source: string;
}
/**
 * @generated from protobuf message gooey.control.v1.PatchMarkupResponse
 */
export interface PatchMarkupResponse {
    /**
     * The Name= identities of the tree after the patch: survivors plus
     * the fragment's names.
     *
     * @generated from protobuf field: repeated string named = 1
     */
    named: string[];
}
/**
 * @generated from protobuf message gooey.control.v1.ListStylesRequest
 */
export interface ListStylesRequest {
}
/**
 * @generated from protobuf message gooey.control.v1.ListStylesResponse
 */
export interface ListStylesResponse {
    /**
     * Sorted by name.
     *
     * @generated from protobuf field: repeated gooey.control.v1.StyleInfo styles = 1
     */
    styles: StyleInfo[];
}
/**
 * @generated from protobuf message gooey.control.v1.ValidateMarkupRequest
 */
export interface ValidateMarkupRequest {
    /**
     * Complete markup source, rooted at <Gooey> with exactly one child.
     *
     * @generated from protobuf field: string source = 1
     */
    source: string;
}
/**
 * @generated from protobuf message gooey.control.v1.ValidateMarkupResponse
 */
export interface ValidateMarkupResponse {
    /**
     * @generated from protobuf field: bool valid = 1
     */
    valid: boolean;
    /**
     * The typed load error when valid is false — the same text a failed
     * SwapMarkup would carry in its status.
     *
     * @generated from protobuf field: string error = 2
     */
    error: string;
    /**
     * The Name= identities the document declares, when valid.
     *
     * @generated from protobuf field: repeated string named = 3
     */
    named: string[];
}
// @generated message type with reflection information, may provide speed optimized methods
class SnapshotTreeRequest$Type extends MessageType<SnapshotTreeRequest> {
    constructor() {
        super("gooey.control.v1.SnapshotTreeRequest", [
            { no: 1, name: "depth", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SnapshotTreeRequest>): SnapshotTreeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.depth = 0;
        if (value !== undefined)
            reflectionMergePartial<SnapshotTreeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SnapshotTreeRequest): SnapshotTreeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 depth */ 1:
                    message.depth = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SnapshotTreeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 depth = 1; */
        if (message.depth !== 0)
            writer.tag(1, WireType.Varint).int32(message.depth);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SnapshotTreeRequest
 */
export const SnapshotTreeRequest = new SnapshotTreeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SnapshotTreeResponse$Type extends MessageType<SnapshotTreeResponse> {
    constructor() {
        super("gooey.control.v1.SnapshotTreeResponse", [
            { no: 1, name: "root", kind: "message", T: () => TreeNode }
        ]);
    }
    create(value?: PartialMessage<SnapshotTreeResponse>): SnapshotTreeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SnapshotTreeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SnapshotTreeResponse): SnapshotTreeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.TreeNode root */ 1:
                    message.root = TreeNode.internalBinaryRead(reader, reader.uint32(), options, message.root);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SnapshotTreeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.TreeNode root = 1; */
        if (message.root)
            TreeNode.internalBinaryWrite(message.root, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SnapshotTreeResponse
 */
export const SnapshotTreeResponse = new SnapshotTreeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScreenTextRequest$Type extends MessageType<ScreenTextRequest> {
    constructor() {
        super("gooey.control.v1.ScreenTextRequest", [
            { no: 1, name: "styled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<ScreenTextRequest>): ScreenTextRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.styled = false;
        if (value !== undefined)
            reflectionMergePartial<ScreenTextRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScreenTextRequest): ScreenTextRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool styled */ 1:
                    message.styled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScreenTextRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool styled = 1; */
        if (message.styled !== false)
            writer.tag(1, WireType.Varint).bool(message.styled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ScreenTextRequest
 */
export const ScreenTextRequest = new ScreenTextRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ScreenTextResponse$Type extends MessageType<ScreenTextResponse> {
    constructor() {
        super("gooey.control.v1.ScreenTextResponse", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ScreenTextResponse>): ScreenTextResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        if (value !== undefined)
            reflectionMergePartial<ScreenTextResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ScreenTextResponse): ScreenTextResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ScreenTextResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ScreenTextResponse
 */
export const ScreenTextResponse = new ScreenTextResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListValuesRequest$Type extends MessageType<ListValuesRequest> {
    constructor() {
        super("gooey.control.v1.ListValuesRequest", []);
    }
    create(value?: PartialMessage<ListValuesRequest>): ListValuesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListValuesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListValuesRequest): ListValuesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListValuesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ListValuesRequest
 */
export const ListValuesRequest = new ListValuesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListValuesResponse$Type extends MessageType<ListValuesResponse> {
    constructor() {
        super("gooey.control.v1.ListValuesResponse", [
            { no: 1, name: "values", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ValueInfo },
            { no: 2, name: "named", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListValuesResponse>): ListValuesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.values = [];
        message.named = [];
        if (value !== undefined)
            reflectionMergePartial<ListValuesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListValuesResponse): ListValuesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated gooey.control.v1.ValueInfo values */ 1:
                    message.values.push(ValueInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated string named */ 2:
                    message.named.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListValuesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated gooey.control.v1.ValueInfo values = 1; */
        for (let i = 0; i < message.values.length; i++)
            ValueInfo.internalBinaryWrite(message.values[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated string named = 2; */
        for (let i = 0; i < message.named.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.named[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ListValuesResponse
 */
export const ListValuesResponse = new ListValuesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPropertyRequest$Type extends MessageType<GetPropertyRequest> {
    constructor() {
        super("gooey.control.v1.GetPropertyRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetPropertyRequest>): GetPropertyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<GetPropertyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPropertyRequest): GetPropertyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPropertyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.GetPropertyRequest
 */
export const GetPropertyRequest = new GetPropertyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetPropertyResponse$Type extends MessageType<GetPropertyResponse> {
    constructor() {
        super("gooey.control.v1.GetPropertyResponse", [
            { no: 1, name: "value", kind: "message", T: () => ValueInfo }
        ]);
    }
    create(value?: PartialMessage<GetPropertyResponse>): GetPropertyResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetPropertyResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetPropertyResponse): GetPropertyResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.ValueInfo value */ 1:
                    message.value = ValueInfo.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetPropertyResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.ValueInfo value = 1; */
        if (message.value)
            ValueInfo.internalBinaryWrite(message.value, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.GetPropertyResponse
 */
export const GetPropertyResponse = new GetPropertyResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetPropertyRequest$Type extends MessageType<SetPropertyRequest> {
    constructor() {
        super("gooey.control.v1.SetPropertyRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "message", T: () => TypedValue }
        ]);
    }
    create(value?: PartialMessage<SetPropertyRequest>): SetPropertyRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<SetPropertyRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetPropertyRequest): SetPropertyRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.TypedValue value */ 2:
                    message.value = TypedValue.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetPropertyRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.TypedValue value = 2; */
        if (message.value)
            TypedValue.internalBinaryWrite(message.value, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SetPropertyRequest
 */
export const SetPropertyRequest = new SetPropertyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetPropertyResponse$Type extends MessageType<SetPropertyResponse> {
    constructor() {
        super("gooey.control.v1.SetPropertyResponse", []);
    }
    create(value?: PartialMessage<SetPropertyResponse>): SetPropertyResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SetPropertyResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetPropertyResponse): SetPropertyResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetPropertyResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SetPropertyResponse
 */
export const SetPropertyResponse = new SetPropertyResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InvokeCommandRequest$Type extends MessageType<InvokeCommandRequest> {
    constructor() {
        super("gooey.control.v1.InvokeCommandRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InvokeCommandRequest>): InvokeCommandRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<InvokeCommandRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InvokeCommandRequest): InvokeCommandRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InvokeCommandRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.InvokeCommandRequest
 */
export const InvokeCommandRequest = new InvokeCommandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InvokeCommandResponse$Type extends MessageType<InvokeCommandResponse> {
    constructor() {
        super("gooey.control.v1.InvokeCommandResponse", []);
    }
    create(value?: PartialMessage<InvokeCommandResponse>): InvokeCommandResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<InvokeCommandResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InvokeCommandResponse): InvokeCommandResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InvokeCommandResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.InvokeCommandResponse
 */
export const InvokeCommandResponse = new InvokeCommandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendKeysRequest$Type extends MessageType<SendKeysRequest> {
    constructor() {
        super("gooey.control.v1.SendKeysRequest", [
            { no: 1, name: "text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "gestures", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SendKeysRequest>): SendKeysRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.text = "";
        message.gestures = [];
        if (value !== undefined)
            reflectionMergePartial<SendKeysRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendKeysRequest): SendKeysRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string text */ 1:
                    message.text = reader.string();
                    break;
                case /* repeated string gestures */ 2:
                    message.gestures.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendKeysRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string text = 1; */
        if (message.text !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.text);
        /* repeated string gestures = 2; */
        for (let i = 0; i < message.gestures.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.gestures[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SendKeysRequest
 */
export const SendKeysRequest = new SendKeysRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendKeysResponse$Type extends MessageType<SendKeysResponse> {
    constructor() {
        super("gooey.control.v1.SendKeysResponse", [
            { no: 1, name: "sent", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "consumed", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SendKeysResponse>): SendKeysResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sent = 0;
        message.consumed = [];
        if (value !== undefined)
            reflectionMergePartial<SendKeysResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendKeysResponse): SendKeysResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 sent */ 1:
                    message.sent = reader.int32();
                    break;
                case /* repeated bool consumed */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.consumed.push(reader.bool());
                    else
                        message.consumed.push(reader.bool());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendKeysResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 sent = 1; */
        if (message.sent !== 0)
            writer.tag(1, WireType.Varint).int32(message.sent);
        /* repeated bool consumed = 2; */
        if (message.consumed.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.consumed.length; i++)
                writer.bool(message.consumed[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SendKeysResponse
 */
export const SendKeysResponse = new SendKeysResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendPointerRequest$Type extends MessageType<SendPointerRequest> {
    constructor() {
        super("gooey.control.v1.SendPointerRequest", [
            { no: 1, name: "event", kind: "message", T: () => PointerEvent }
        ]);
    }
    create(value?: PartialMessage<SendPointerRequest>): SendPointerRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SendPointerRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendPointerRequest): SendPointerRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.PointerEvent event */ 1:
                    message.event = PointerEvent.internalBinaryRead(reader, reader.uint32(), options, message.event);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendPointerRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.PointerEvent event = 1; */
        if (message.event)
            PointerEvent.internalBinaryWrite(message.event, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SendPointerRequest
 */
export const SendPointerRequest = new SendPointerRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendPointerResponse$Type extends MessageType<SendPointerResponse> {
    constructor() {
        super("gooey.control.v1.SendPointerResponse", [
            { no: 1, name: "consumed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SendPointerResponse>): SendPointerResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.consumed = false;
        if (value !== undefined)
            reflectionMergePartial<SendPointerResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendPointerResponse): SendPointerResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool consumed */ 1:
                    message.consumed = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendPointerResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool consumed = 1; */
        if (message.consumed !== false)
            writer.tag(1, WireType.Varint).bool(message.consumed);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SendPointerResponse
 */
export const SendPointerResponse = new SendPointerResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetFocusRequest$Type extends MessageType<SetFocusRequest> {
    constructor() {
        super("gooey.control.v1.SetFocusRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SetFocusRequest>): SetFocusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<SetFocusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetFocusRequest): SetFocusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetFocusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SetFocusRequest
 */
export const SetFocusRequest = new SetFocusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetFocusResponse$Type extends MessageType<SetFocusResponse> {
    constructor() {
        super("gooey.control.v1.SetFocusResponse", []);
    }
    create(value?: PartialMessage<SetFocusResponse>): SetFocusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<SetFocusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetFocusResponse): SetFocusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetFocusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SetFocusResponse
 */
export const SetFocusResponse = new SetFocusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SwapMarkupRequest$Type extends MessageType<SwapMarkupRequest> {
    constructor() {
        super("gooey.control.v1.SwapMarkupRequest", [
            { no: 1, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "register", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PropertyRegistration }
        ]);
    }
    create(value?: PartialMessage<SwapMarkupRequest>): SwapMarkupRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.source = "";
        message.register = [];
        if (value !== undefined)
            reflectionMergePartial<SwapMarkupRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SwapMarkupRequest): SwapMarkupRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string source */ 1:
                    message.source = reader.string();
                    break;
                case /* repeated gooey.control.v1.PropertyRegistration register */ 2:
                    message.register.push(PropertyRegistration.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SwapMarkupRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string source = 1; */
        if (message.source !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.source);
        /* repeated gooey.control.v1.PropertyRegistration register = 2; */
        for (let i = 0; i < message.register.length; i++)
            PropertyRegistration.internalBinaryWrite(message.register[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SwapMarkupRequest
 */
export const SwapMarkupRequest = new SwapMarkupRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SwapMarkupResponse$Type extends MessageType<SwapMarkupResponse> {
    constructor() {
        super("gooey.control.v1.SwapMarkupResponse", [
            { no: 1, name: "named", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SwapMarkupResponse>): SwapMarkupResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.named = [];
        if (value !== undefined)
            reflectionMergePartial<SwapMarkupResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SwapMarkupResponse): SwapMarkupResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string named */ 1:
                    message.named.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SwapMarkupResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string named = 1; */
        for (let i = 0; i < message.named.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.named[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.SwapMarkupResponse
 */
export const SwapMarkupResponse = new SwapMarkupResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterPropertiesRequest$Type extends MessageType<RegisterPropertiesRequest> {
    constructor() {
        super("gooey.control.v1.RegisterPropertiesRequest", [
            { no: 1, name: "properties", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PropertyRegistration }
        ]);
    }
    create(value?: PartialMessage<RegisterPropertiesRequest>): RegisterPropertiesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.properties = [];
        if (value !== undefined)
            reflectionMergePartial<RegisterPropertiesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterPropertiesRequest): RegisterPropertiesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated gooey.control.v1.PropertyRegistration properties */ 1:
                    message.properties.push(PropertyRegistration.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterPropertiesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated gooey.control.v1.PropertyRegistration properties = 1; */
        for (let i = 0; i < message.properties.length; i++)
            PropertyRegistration.internalBinaryWrite(message.properties[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.RegisterPropertiesRequest
 */
export const RegisterPropertiesRequest = new RegisterPropertiesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterPropertiesResponse$Type extends MessageType<RegisterPropertiesResponse> {
    constructor() {
        super("gooey.control.v1.RegisterPropertiesResponse", []);
    }
    create(value?: PartialMessage<RegisterPropertiesResponse>): RegisterPropertiesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RegisterPropertiesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterPropertiesResponse): RegisterPropertiesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterPropertiesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.RegisterPropertiesResponse
 */
export const RegisterPropertiesResponse = new RegisterPropertiesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnregisterNamesRequest$Type extends MessageType<UnregisterNamesRequest> {
    constructor() {
        super("gooey.control.v1.UnregisterNamesRequest", [
            { no: 1, name: "names", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<UnregisterNamesRequest>): UnregisterNamesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.names = [];
        if (value !== undefined)
            reflectionMergePartial<UnregisterNamesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UnregisterNamesRequest): UnregisterNamesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string names */ 1:
                    message.names.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UnregisterNamesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string names = 1; */
        for (let i = 0; i < message.names.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.names[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.UnregisterNamesRequest
 */
export const UnregisterNamesRequest = new UnregisterNamesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnregisterNamesResponse$Type extends MessageType<UnregisterNamesResponse> {
    constructor() {
        super("gooey.control.v1.UnregisterNamesResponse", []);
    }
    create(value?: PartialMessage<UnregisterNamesResponse>): UnregisterNamesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UnregisterNamesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UnregisterNamesResponse): UnregisterNamesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UnregisterNamesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.UnregisterNamesResponse
 */
export const UnregisterNamesResponse = new UnregisterNamesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDeclaredSchemaRequest$Type extends MessageType<GetDeclaredSchemaRequest> {
    constructor() {
        super("gooey.control.v1.GetDeclaredSchemaRequest", [
            { no: 1, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetDeclaredSchemaRequest>): GetDeclaredSchemaRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.source = "";
        if (value !== undefined)
            reflectionMergePartial<GetDeclaredSchemaRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDeclaredSchemaRequest): GetDeclaredSchemaRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string source */ 1:
                    message.source = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDeclaredSchemaRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string source = 1; */
        if (message.source !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.source);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.GetDeclaredSchemaRequest
 */
export const GetDeclaredSchemaRequest = new GetDeclaredSchemaRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDeclaredSchemaResponse$Type extends MessageType<GetDeclaredSchemaResponse> {
    constructor() {
        super("gooey.control.v1.GetDeclaredSchemaResponse", [
            { no: 1, name: "schema", kind: "message", T: () => ControlSchema }
        ]);
    }
    create(value?: PartialMessage<GetDeclaredSchemaResponse>): GetDeclaredSchemaResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDeclaredSchemaResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDeclaredSchemaResponse): GetDeclaredSchemaResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.ControlSchema schema */ 1:
                    message.schema = ControlSchema.internalBinaryRead(reader, reader.uint32(), options, message.schema);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDeclaredSchemaResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.ControlSchema schema = 1; */
        if (message.schema)
            ControlSchema.internalBinaryWrite(message.schema, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.GetDeclaredSchemaResponse
 */
export const GetDeclaredSchemaResponse = new GetDeclaredSchemaResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatchMarkupRequest$Type extends MessageType<PatchMarkupRequest> {
    constructor() {
        super("gooey.control.v1.PatchMarkupRequest", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PatchMarkupRequest>): PatchMarkupRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.source = "";
        if (value !== undefined)
            reflectionMergePartial<PatchMarkupRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatchMarkupRequest): PatchMarkupRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string source */ 2:
                    message.source = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatchMarkupRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string source = 2; */
        if (message.source !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.source);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.PatchMarkupRequest
 */
export const PatchMarkupRequest = new PatchMarkupRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PatchMarkupResponse$Type extends MessageType<PatchMarkupResponse> {
    constructor() {
        super("gooey.control.v1.PatchMarkupResponse", [
            { no: 1, name: "named", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PatchMarkupResponse>): PatchMarkupResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.named = [];
        if (value !== undefined)
            reflectionMergePartial<PatchMarkupResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PatchMarkupResponse): PatchMarkupResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string named */ 1:
                    message.named.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PatchMarkupResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string named = 1; */
        for (let i = 0; i < message.named.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.named[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.PatchMarkupResponse
 */
export const PatchMarkupResponse = new PatchMarkupResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListStylesRequest$Type extends MessageType<ListStylesRequest> {
    constructor() {
        super("gooey.control.v1.ListStylesRequest", []);
    }
    create(value?: PartialMessage<ListStylesRequest>): ListStylesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListStylesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListStylesRequest): ListStylesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListStylesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ListStylesRequest
 */
export const ListStylesRequest = new ListStylesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListStylesResponse$Type extends MessageType<ListStylesResponse> {
    constructor() {
        super("gooey.control.v1.ListStylesResponse", [
            { no: 1, name: "styles", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => StyleInfo }
        ]);
    }
    create(value?: PartialMessage<ListStylesResponse>): ListStylesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.styles = [];
        if (value !== undefined)
            reflectionMergePartial<ListStylesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListStylesResponse): ListStylesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated gooey.control.v1.StyleInfo styles */ 1:
                    message.styles.push(StyleInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListStylesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated gooey.control.v1.StyleInfo styles = 1; */
        for (let i = 0; i < message.styles.length; i++)
            StyleInfo.internalBinaryWrite(message.styles[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ListStylesResponse
 */
export const ListStylesResponse = new ListStylesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateMarkupRequest$Type extends MessageType<ValidateMarkupRequest> {
    constructor() {
        super("gooey.control.v1.ValidateMarkupRequest", [
            { no: 1, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ValidateMarkupRequest>): ValidateMarkupRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.source = "";
        if (value !== undefined)
            reflectionMergePartial<ValidateMarkupRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateMarkupRequest): ValidateMarkupRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string source */ 1:
                    message.source = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateMarkupRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string source = 1; */
        if (message.source !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.source);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ValidateMarkupRequest
 */
export const ValidateMarkupRequest = new ValidateMarkupRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateMarkupResponse$Type extends MessageType<ValidateMarkupResponse> {
    constructor() {
        super("gooey.control.v1.ValidateMarkupResponse", [
            { no: 1, name: "valid", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "named", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ValidateMarkupResponse>): ValidateMarkupResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.valid = false;
        message.error = "";
        message.named = [];
        if (value !== undefined)
            reflectionMergePartial<ValidateMarkupResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateMarkupResponse): ValidateMarkupResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool valid */ 1:
                    message.valid = reader.bool();
                    break;
                case /* string error */ 2:
                    message.error = reader.string();
                    break;
                case /* repeated string named */ 3:
                    message.named.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateMarkupResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool valid = 1; */
        if (message.valid !== false)
            writer.tag(1, WireType.Varint).bool(message.valid);
        /* string error = 2; */
        if (message.error !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.error);
        /* repeated string named = 3; */
        for (let i = 0; i < message.named.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.named[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ValidateMarkupResponse
 */
export const ValidateMarkupResponse = new ValidateMarkupResponse$Type();
/**
 * @generated ServiceType for protobuf service gooey.control.v1.ControlService
 */
export const ControlService = new ServiceType("gooey.control.v1.ControlService", [
    { name: "SnapshotTree", options: {}, I: SnapshotTreeRequest, O: SnapshotTreeResponse },
    { name: "ScreenText", options: {}, I: ScreenTextRequest, O: ScreenTextResponse },
    { name: "ListValues", options: {}, I: ListValuesRequest, O: ListValuesResponse },
    { name: "GetProperty", options: {}, I: GetPropertyRequest, O: GetPropertyResponse },
    { name: "SetProperty", options: {}, I: SetPropertyRequest, O: SetPropertyResponse },
    { name: "InvokeCommand", options: {}, I: InvokeCommandRequest, O: InvokeCommandResponse },
    { name: "SendKeys", options: {}, I: SendKeysRequest, O: SendKeysResponse },
    { name: "SendPointer", options: {}, I: SendPointerRequest, O: SendPointerResponse },
    { name: "SetFocus", options: {}, I: SetFocusRequest, O: SetFocusResponse },
    { name: "SwapMarkup", options: {}, I: SwapMarkupRequest, O: SwapMarkupResponse },
    { name: "RegisterProperties", options: {}, I: RegisterPropertiesRequest, O: RegisterPropertiesResponse },
    { name: "UnregisterNames", options: {}, I: UnregisterNamesRequest, O: UnregisterNamesResponse },
    { name: "GetDeclaredSchema", options: {}, I: GetDeclaredSchemaRequest, O: GetDeclaredSchemaResponse },
    { name: "PatchMarkup", options: {}, I: PatchMarkupRequest, O: PatchMarkupResponse },
    { name: "ListStyles", options: {}, I: ListStylesRequest, O: ListStylesResponse },
    { name: "ValidateMarkup", options: {}, I: ValidateMarkupRequest, O: ValidateMarkupResponse }
]);
