// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "gooey/control/v1/control.proto" (package "gooey.control.v1", syntax proto3)
// tslint:disable
//
// ControlService — the unary control plane.
//
// Every RPC here is one request, one settled answer: the server
// marshals the call onto the app's UI goroutine, waits for the settle
// barrier (the frame the call's Sets asked for has been composed), and
// only then answers. Reading the screen immediately after invoking a
// command therefore sees the new pixels — the same guarantee the MCP
// bridge gives today, promoted to the contract.
//
// Errors are gRPC status codes, not payload fields:
//   NOT_FOUND            — no such name in the binding context / tree
//   INVALID_ARGUMENT     — type mismatch (message names both types),
//                          bad markup, bad gesture, bad registration
//   FAILED_PRECONDITION  — no markup context, no live composition
//   DEADLINE_EXCEEDED    — the UI goroutine did not answer in time
//                          (the run loop is blocked or not running)
//
import { ControlService } from "./control";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { GetDeclaredSchemaResponse } from "./control";
import type { GetDeclaredSchemaRequest } from "./control";
import type { RegisterPropertiesResponse } from "./control";
import type { RegisterPropertiesRequest } from "./control";
import type { SwapMarkupResponse } from "./control";
import type { SwapMarkupRequest } from "./control";
import type { SetFocusResponse } from "./control";
import type { SetFocusRequest } from "./control";
import type { SendPointerResponse } from "./control";
import type { SendPointerRequest } from "./control";
import type { SendKeysResponse } from "./control";
import type { SendKeysRequest } from "./control";
import type { InvokeCommandResponse } from "./control";
import type { InvokeCommandRequest } from "./control";
import type { SetPropertyResponse } from "./control";
import type { SetPropertyRequest } from "./control";
import type { GetPropertyResponse } from "./control";
import type { GetPropertyRequest } from "./control";
import type { ListValuesResponse } from "./control";
import type { ListValuesRequest } from "./control";
import type { ScreenTextResponse } from "./control";
import type { ScreenTextRequest } from "./control";
import type { SnapshotTreeResponse } from "./control";
import type { SnapshotTreeRequest } from "./control";
import * as grpc from "@grpc/grpc-js";
/**
 * ControlService is the request/response surface of a running gooey
 * app. The MCP tools (issue #112) are a thin adapter over exactly
 * these RPCs; nothing an MCP tool can do is absent here, and nothing
 * here needs MCP.
 *
 * @generated from protobuf service gooey.control.v1.ControlService
 */
export interface IControlServiceClient {
    /**
     * SnapshotTree serializes the live component tree — MCP tree_snapshot.
     *
     * @generated from protobuf rpc: SnapshotTree
     */
    snapshotTree(input: SnapshotTreeRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SnapshotTreeResponse) => void): grpc.ClientUnaryCall;
    snapshotTree(input: SnapshotTreeRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SnapshotTreeResponse) => void): grpc.ClientUnaryCall;
    snapshotTree(input: SnapshotTreeRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SnapshotTreeResponse) => void): grpc.ClientUnaryCall;
    snapshotTree(input: SnapshotTreeRequest, callback: (err: grpc.ServiceError | null, value?: SnapshotTreeResponse) => void): grpc.ClientUnaryCall;
    /**
     * ScreenText reads the retained cell plane as of the last composed
     * frame — MCP screen_text. Never composes a frame of its own: doing
     * so would mark dirty nodes clean and steal the app's damage counts.
     *
     * @generated from protobuf rpc: ScreenText
     */
    screenText(input: ScreenTextRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ScreenTextResponse) => void): grpc.ClientUnaryCall;
    screenText(input: ScreenTextRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: ScreenTextResponse) => void): grpc.ClientUnaryCall;
    screenText(input: ScreenTextRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ScreenTextResponse) => void): grpc.ClientUnaryCall;
    screenText(input: ScreenTextRequest, callback: (err: grpc.ServiceError | null, value?: ScreenTextResponse) => void): grpc.ClientUnaryCall;
    /**
     * ListValues describes the bindable surface — MCP list_values.
     *
     * @generated from protobuf rpc: ListValues
     */
    listValues(input: ListValuesRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListValuesResponse) => void): grpc.ClientUnaryCall;
    listValues(input: ListValuesRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: ListValuesResponse) => void): grpc.ClientUnaryCall;
    listValues(input: ListValuesRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListValuesResponse) => void): grpc.ClientUnaryCall;
    listValues(input: ListValuesRequest, callback: (err: grpc.ServiceError | null, value?: ListValuesResponse) => void): grpc.ClientUnaryCall;
    /**
     * GetProperty reads one named property. New surface (MCP reads via
     * list_values); the natural unary read half of SetProperty.
     *
     * @generated from protobuf rpc: GetProperty
     */
    getProperty(input: GetPropertyRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetPropertyResponse) => void): grpc.ClientUnaryCall;
    getProperty(input: GetPropertyRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetPropertyResponse) => void): grpc.ClientUnaryCall;
    getProperty(input: GetPropertyRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetPropertyResponse) => void): grpc.ClientUnaryCall;
    getProperty(input: GetPropertyRequest, callback: (err: grpc.ServiceError | null, value?: GetPropertyResponse) => void): grpc.ClientUnaryCall;
    /**
     * SetProperty writes one named source property — MCP set_value. The
     * TypedValue's case must match the handle's type; a mismatch is
     * INVALID_ARGUMENT naming both sides, and nothing changes.
     *
     * @generated from protobuf rpc: SetProperty
     */
    setProperty(input: SetPropertyRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SetPropertyResponse) => void): grpc.ClientUnaryCall;
    setProperty(input: SetPropertyRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SetPropertyResponse) => void): grpc.ClientUnaryCall;
    setProperty(input: SetPropertyRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SetPropertyResponse) => void): grpc.ClientUnaryCall;
    setProperty(input: SetPropertyRequest, callback: (err: grpc.ServiceError | null, value?: SetPropertyResponse) => void): grpc.ClientUnaryCall;
    /**
     * InvokeCommand runs a named command — MCP invoke_command.
     *
     * @generated from protobuf rpc: InvokeCommand
     */
    invokeCommand(input: InvokeCommandRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: InvokeCommandResponse) => void): grpc.ClientUnaryCall;
    invokeCommand(input: InvokeCommandRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: InvokeCommandResponse) => void): grpc.ClientUnaryCall;
    invokeCommand(input: InvokeCommandRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: InvokeCommandResponse) => void): grpc.ClientUnaryCall;
    invokeCommand(input: InvokeCommandRequest, callback: (err: grpc.ServiceError | null, value?: InvokeCommandResponse) => void): grpc.ClientUnaryCall;
    /**
     * SendKeys injects key events into the app's single ordered input
     * stream — MCP send_keys. Routed through the composition, not the
     * app-level handler: a client cannot reach the quit key.
     *
     * @generated from protobuf rpc: SendKeys
     */
    sendKeys(input: SendKeysRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendKeysResponse) => void): grpc.ClientUnaryCall;
    sendKeys(input: SendKeysRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SendKeysResponse) => void): grpc.ClientUnaryCall;
    sendKeys(input: SendKeysRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendKeysResponse) => void): grpc.ClientUnaryCall;
    sendKeys(input: SendKeysRequest, callback: (err: grpc.ServiceError | null, value?: SendKeysResponse) => void): grpc.ClientUnaryCall;
    /**
     * SendPointer injects one pointer event — MCP send_mouse.
     *
     * @generated from protobuf rpc: SendPointer
     */
    sendPointer(input: SendPointerRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendPointerResponse) => void): grpc.ClientUnaryCall;
    sendPointer(input: SendPointerRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SendPointerResponse) => void): grpc.ClientUnaryCall;
    sendPointer(input: SendPointerRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendPointerResponse) => void): grpc.ClientUnaryCall;
    sendPointer(input: SendPointerRequest, callback: (err: grpc.ServiceError | null, value?: SendPointerResponse) => void): grpc.ClientUnaryCall;
    /**
     * SetFocus moves keyboard focus to a named element — MCP focus.
     *
     * @generated from protobuf rpc: SetFocus
     */
    setFocus(input: SetFocusRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SetFocusResponse) => void): grpc.ClientUnaryCall;
    setFocus(input: SetFocusRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SetFocusResponse) => void): grpc.ClientUnaryCall;
    setFocus(input: SetFocusRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SetFocusResponse) => void): grpc.ClientUnaryCall;
    setFocus(input: SetFocusRequest, callback: (err: grpc.ServiceError | null, value?: SetFocusResponse) => void): grpc.ClientUnaryCall;
    /**
     * SwapMarkup replaces the page with new markup built against the
     * app's existing binding context — MCP swap_markup. Optional
     * registrations grow the viewmodel first (issue #89). Atomic: a
     * failed build leaves the running tree, the name table AND the
     * registrations untouched.
     *
     * @generated from protobuf rpc: SwapMarkup
     */
    swapMarkup(input: SwapMarkupRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SwapMarkupResponse) => void): grpc.ClientUnaryCall;
    swapMarkup(input: SwapMarkupRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SwapMarkupResponse) => void): grpc.ClientUnaryCall;
    swapMarkup(input: SwapMarkupRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SwapMarkupResponse) => void): grpc.ClientUnaryCall;
    swapMarkup(input: SwapMarkupRequest, callback: (err: grpc.ServiceError | null, value?: SwapMarkupResponse) => void): grpc.ClientUnaryCall;
    /**
     * RegisterProperties materializes new typed source properties in the
     * binding context without swapping markup (issue #89). A name that
     * already exists is INVALID_ARGUMENT — one source of truth.
     *
     * @generated from protobuf rpc: RegisterProperties
     */
    registerProperties(input: RegisterPropertiesRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: RegisterPropertiesResponse) => void): grpc.ClientUnaryCall;
    registerProperties(input: RegisterPropertiesRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: RegisterPropertiesResponse) => void): grpc.ClientUnaryCall;
    registerProperties(input: RegisterPropertiesRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: RegisterPropertiesResponse) => void): grpc.ClientUnaryCall;
    registerProperties(input: RegisterPropertiesRequest, callback: (err: grpc.ServiceError | null, value?: RegisterPropertiesResponse) => void): grpc.ClientUnaryCall;
    /**
     * GetDeclaredSchema returns a document's <x:Property> declaration
     * block as a schema (issue #62): the contract a values payload must
     * satisfy before the document can build.
     *
     * @generated from protobuf rpc: GetDeclaredSchema
     */
    getDeclaredSchema(input: GetDeclaredSchemaRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetDeclaredSchemaResponse) => void): grpc.ClientUnaryCall;
    getDeclaredSchema(input: GetDeclaredSchemaRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetDeclaredSchemaResponse) => void): grpc.ClientUnaryCall;
    getDeclaredSchema(input: GetDeclaredSchemaRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetDeclaredSchemaResponse) => void): grpc.ClientUnaryCall;
    getDeclaredSchema(input: GetDeclaredSchemaRequest, callback: (err: grpc.ServiceError | null, value?: GetDeclaredSchemaResponse) => void): grpc.ClientUnaryCall;
}
/**
 * ControlService is the request/response surface of a running gooey
 * app. The MCP tools (issue #112) are a thin adapter over exactly
 * these RPCs; nothing an MCP tool can do is absent here, and nothing
 * here needs MCP.
 *
 * @generated from protobuf service gooey.control.v1.ControlService
 */
export class ControlServiceClient extends grpc.Client implements IControlServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * SnapshotTree serializes the live component tree — MCP tree_snapshot.
     *
     * @generated from protobuf rpc: SnapshotTree
     */
    snapshotTree(input: SnapshotTreeRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SnapshotTreeResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SnapshotTreeResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SnapshotTreeResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[0];
        return this.makeUnaryRequest<SnapshotTreeRequest, SnapshotTreeResponse>(`/${ControlService.typeName}/${method.name}`, (value: SnapshotTreeRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SnapshotTreeResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * ScreenText reads the retained cell plane as of the last composed
     * frame — MCP screen_text. Never composes a frame of its own: doing
     * so would mark dirty nodes clean and steal the app's damage counts.
     *
     * @generated from protobuf rpc: ScreenText
     */
    screenText(input: ScreenTextRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ScreenTextResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ScreenTextResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: ScreenTextResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[1];
        return this.makeUnaryRequest<ScreenTextRequest, ScreenTextResponse>(`/${ControlService.typeName}/${method.name}`, (value: ScreenTextRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): ScreenTextResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * ListValues describes the bindable surface — MCP list_values.
     *
     * @generated from protobuf rpc: ListValues
     */
    listValues(input: ListValuesRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListValuesResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListValuesResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: ListValuesResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[2];
        return this.makeUnaryRequest<ListValuesRequest, ListValuesResponse>(`/${ControlService.typeName}/${method.name}`, (value: ListValuesRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): ListValuesResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * GetProperty reads one named property. New surface (MCP reads via
     * list_values); the natural unary read half of SetProperty.
     *
     * @generated from protobuf rpc: GetProperty
     */
    getProperty(input: GetPropertyRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetPropertyResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetPropertyResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetPropertyResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[3];
        return this.makeUnaryRequest<GetPropertyRequest, GetPropertyResponse>(`/${ControlService.typeName}/${method.name}`, (value: GetPropertyRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetPropertyResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * SetProperty writes one named source property — MCP set_value. The
     * TypedValue's case must match the handle's type; a mismatch is
     * INVALID_ARGUMENT naming both sides, and nothing changes.
     *
     * @generated from protobuf rpc: SetProperty
     */
    setProperty(input: SetPropertyRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SetPropertyResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SetPropertyResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SetPropertyResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[4];
        return this.makeUnaryRequest<SetPropertyRequest, SetPropertyResponse>(`/${ControlService.typeName}/${method.name}`, (value: SetPropertyRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SetPropertyResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * InvokeCommand runs a named command — MCP invoke_command.
     *
     * @generated from protobuf rpc: InvokeCommand
     */
    invokeCommand(input: InvokeCommandRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: InvokeCommandResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: InvokeCommandResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: InvokeCommandResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[5];
        return this.makeUnaryRequest<InvokeCommandRequest, InvokeCommandResponse>(`/${ControlService.typeName}/${method.name}`, (value: InvokeCommandRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): InvokeCommandResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * SendKeys injects key events into the app's single ordered input
     * stream — MCP send_keys. Routed through the composition, not the
     * app-level handler: a client cannot reach the quit key.
     *
     * @generated from protobuf rpc: SendKeys
     */
    sendKeys(input: SendKeysRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendKeysResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendKeysResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SendKeysResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[6];
        return this.makeUnaryRequest<SendKeysRequest, SendKeysResponse>(`/${ControlService.typeName}/${method.name}`, (value: SendKeysRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SendKeysResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * SendPointer injects one pointer event — MCP send_mouse.
     *
     * @generated from protobuf rpc: SendPointer
     */
    sendPointer(input: SendPointerRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendPointerResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendPointerResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SendPointerResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[7];
        return this.makeUnaryRequest<SendPointerRequest, SendPointerResponse>(`/${ControlService.typeName}/${method.name}`, (value: SendPointerRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SendPointerResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * SetFocus moves keyboard focus to a named element — MCP focus.
     *
     * @generated from protobuf rpc: SetFocus
     */
    setFocus(input: SetFocusRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SetFocusResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SetFocusResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SetFocusResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[8];
        return this.makeUnaryRequest<SetFocusRequest, SetFocusResponse>(`/${ControlService.typeName}/${method.name}`, (value: SetFocusRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SetFocusResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * SwapMarkup replaces the page with new markup built against the
     * app's existing binding context — MCP swap_markup. Optional
     * registrations grow the viewmodel first (issue #89). Atomic: a
     * failed build leaves the running tree, the name table AND the
     * registrations untouched.
     *
     * @generated from protobuf rpc: SwapMarkup
     */
    swapMarkup(input: SwapMarkupRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SwapMarkupResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SwapMarkupResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SwapMarkupResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[9];
        return this.makeUnaryRequest<SwapMarkupRequest, SwapMarkupResponse>(`/${ControlService.typeName}/${method.name}`, (value: SwapMarkupRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SwapMarkupResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * RegisterProperties materializes new typed source properties in the
     * binding context without swapping markup (issue #89). A name that
     * already exists is INVALID_ARGUMENT — one source of truth.
     *
     * @generated from protobuf rpc: RegisterProperties
     */
    registerProperties(input: RegisterPropertiesRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: RegisterPropertiesResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: RegisterPropertiesResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: RegisterPropertiesResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[10];
        return this.makeUnaryRequest<RegisterPropertiesRequest, RegisterPropertiesResponse>(`/${ControlService.typeName}/${method.name}`, (value: RegisterPropertiesRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): RegisterPropertiesResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * GetDeclaredSchema returns a document's <x:Property> declaration
     * block as a schema (issue #62): the contract a values payload must
     * satisfy before the document can build.
     *
     * @generated from protobuf rpc: GetDeclaredSchema
     */
    getDeclaredSchema(input: GetDeclaredSchemaRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetDeclaredSchemaResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetDeclaredSchemaResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetDeclaredSchemaResponse) => void)): grpc.ClientUnaryCall {
        const method = ControlService.methods[11];
        return this.makeUnaryRequest<GetDeclaredSchemaRequest, GetDeclaredSchemaResponse>(`/${ControlService.typeName}/${method.name}`, (value: GetDeclaredSchemaRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetDeclaredSchemaResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
