// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "gooey/control/v1/session.proto" (package "gooey.control.v1", syntax proto3)
// tslint:disable
//
// SessionService — the streaming control plane.
//
// One bidi stream, mirroring the framework's own shape: the client
// side is ONE ordered stream of acts, exactly as the terminal is one
// ordered input.Event stream; the server side is one ordered stream of
// events, framed on the app's composed frames.
//
// The consistency rule (issue #49's torn-read lesson): everything that
// changed within one composed frame — property deltas, damage, the
// structure swap that caused them — arrives in ONE FrameDelta message.
// A client can never observe values without the frame they belong to,
// by construction; there is no delta channel to tear away from its
// markup.
//
import { SessionService } from "./session";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { AttachResponse } from "./session";
import type { AttachRequest } from "./session";
import * as grpc from "@grpc/grpc-js";
/**
 * SessionService attaches a client to a running app for the lifetime
 * of the stream. Push replaces polling (issue #49): a subscribed
 * client hears about a change when the frame containing it composes,
 * not on the next 400ms tick.
 *
 * @generated from protobuf service gooey.control.v1.SessionService
 */
export interface ISessionServiceClient {
    /**
     * Attach opens a session. The first client message must be
     * `subscribe`; every later one is an `act`. Server messages start
     * with `welcome` and then interleave act results with subscribed
     * events. Closing either direction ends the session; the app
     * outlives every session.
     *
     * @generated from protobuf rpc: Attach
     */
    attach(metadata: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientDuplexStream<AttachRequest, AttachResponse>;
    attach(options?: grpc.CallOptions): grpc.ClientDuplexStream<AttachRequest, AttachResponse>;
}
/**
 * SessionService attaches a client to a running app for the lifetime
 * of the stream. Push replaces polling (issue #49): a subscribed
 * client hears about a change when the frame containing it composes,
 * not on the next 400ms tick.
 *
 * @generated from protobuf service gooey.control.v1.SessionService
 */
export class SessionServiceClient extends grpc.Client implements ISessionServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * Attach opens a session. The first client message must be
     * `subscribe`; every later one is an `act`. Server messages start
     * with `welcome` and then interleave act results with subscribed
     * events. Closing either direction ends the session; the app
     * outlives every session.
     *
     * @generated from protobuf rpc: Attach
     */
    attach(metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientDuplexStream<AttachRequest, AttachResponse> {
        const method = SessionService.methods[0];
        return this.makeBidiStreamRequest<AttachRequest, AttachResponse>(`/${SessionService.typeName}/${method.name}`, (value: AttachRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): AttachResponse => method.O.fromBinary(value, this._binaryOptions), (metadata as any), options);
    }
}
