// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "gooey/control/v1/session.proto" (package "gooey.control.v1", syntax proto3)
// tslint:disable
//
// SessionService — the streaming control plane.
//
// One bidi stream, mirroring the framework's own shape: the client
// side is ONE ordered stream of acts, exactly as the terminal is one
// ordered input.Event stream; the server side is one ordered stream of
// events, framed on the app's composed frames.
//
// The consistency rule (issue #49's torn-read lesson): everything that
// changed within one composed frame — property deltas, damage, the
// structure swap that caused them — arrives in ONE FrameDelta message.
// A client can never observe values without the frame they belong to,
// by construction; there is no delta channel to tear away from its
// markup.
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { InputEvent } from "./types";
import { Rect } from "./types";
import { PropertyChange } from "./types";
import { RegisterPropertiesResponse } from "./control";
import { SwapMarkupResponse } from "./control";
import { SetFocusResponse } from "./control";
import { SendPointerResponse } from "./control";
import { SendKeysResponse } from "./control";
import { InvokeCommandResponse } from "./control";
import { SetPropertyResponse } from "./control";
import { RegisterPropertiesRequest } from "./control";
import { SwapMarkupRequest } from "./control";
import { SetFocusRequest } from "./control";
import { SendPointerRequest } from "./control";
import { SendKeysRequest } from "./control";
import { InvokeCommandRequest } from "./control";
import { SetPropertyRequest } from "./control";
/**
 * @generated from protobuf message gooey.control.v1.AttachRequest
 */
export interface AttachRequest {
    /**
     * @generated from protobuf oneof: msg
     */
    msg: {
        oneofKind: "subscribe";
        /**
         * First message only; a second subscribe is INVALID_ARGUMENT.
         *
         * @generated from protobuf field: gooey.control.v1.Subscription subscribe = 1
         */
        subscribe: Subscription;
    } | {
        oneofKind: "act";
        /**
         * @generated from protobuf field: gooey.control.v1.Act act = 2
         */
        act: Act;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Subscription selects the event channels this session receives.
 * Everything is opt-in; an all-defaults Subscription receives only
 * welcome and act results — a write-only session.
 *
 * @generated from protobuf message gooey.control.v1.Subscription
 */
export interface Subscription {
    /**
     * Property deltas, delivered inside FrameDelta.
     *
     * @generated from protobuf field: bool properties = 1
     */
    properties: boolean;
    /**
     * Restrict property deltas to these dotted names; empty means all.
     *
     * @generated from protobuf field: repeated string names = 2
     */
    names: string[];
    /**
     * Frame events (damage rects, repaint counts) even when no
     * subscribed property changed.
     *
     * @generated from protobuf field: bool frames = 3
     */
    frames: boolean;
    /**
     * Echo of the app's input stream (terminal AND remote), as consumed.
     *
     * @generated from protobuf field: bool input = 4
     */
    input: boolean;
    /**
     * Lifecycle: resize, markup swap, shutdown.
     *
     * @generated from protobuf field: bool lifecycle = 5
     */
    lifecycle: boolean;
}
/**
 * Act is one client action. Acts are applied in stream order on the
 * UI goroutine — the remote mirror of the one ordered input stream —
 * and each is answered by exactly one ActResult carrying the same id.
 *
 * @generated from protobuf message gooey.control.v1.Act
 */
export interface Act {
    /**
     * Client-assigned correlation id, echoed in the ActResult.
     *
     * @generated from protobuf field: uint64 id = 1
     */
    id: bigint;
    /**
     * The same request messages the unary surface takes: one model, two
     * transports.
     *
     * @generated from protobuf oneof: act
     */
    act: {
        oneofKind: "setProperty";
        /**
         * @generated from protobuf field: gooey.control.v1.SetPropertyRequest set_property = 2
         */
        setProperty: SetPropertyRequest;
    } | {
        oneofKind: "invokeCommand";
        /**
         * @generated from protobuf field: gooey.control.v1.InvokeCommandRequest invoke_command = 3
         */
        invokeCommand: InvokeCommandRequest;
    } | {
        oneofKind: "sendKeys";
        /**
         * @generated from protobuf field: gooey.control.v1.SendKeysRequest send_keys = 4
         */
        sendKeys: SendKeysRequest;
    } | {
        oneofKind: "sendPointer";
        /**
         * @generated from protobuf field: gooey.control.v1.SendPointerRequest send_pointer = 5
         */
        sendPointer: SendPointerRequest;
    } | {
        oneofKind: "setFocus";
        /**
         * @generated from protobuf field: gooey.control.v1.SetFocusRequest set_focus = 6
         */
        setFocus: SetFocusRequest;
    } | {
        oneofKind: "swapMarkup";
        /**
         * @generated from protobuf field: gooey.control.v1.SwapMarkupRequest swap_markup = 7
         */
        swapMarkup: SwapMarkupRequest;
    } | {
        oneofKind: "registerProperties";
        /**
         * @generated from protobuf field: gooey.control.v1.RegisterPropertiesRequest register_properties = 8
         */
        registerProperties: RegisterPropertiesRequest;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message gooey.control.v1.AttachResponse
 */
export interface AttachResponse {
    /**
     * @generated from protobuf oneof: msg
     */
    msg: {
        oneofKind: "welcome";
        /**
         * @generated from protobuf field: gooey.control.v1.Welcome welcome = 1
         */
        welcome: Welcome;
    } | {
        oneofKind: "result";
        /**
         * @generated from protobuf field: gooey.control.v1.ActResult result = 2
         */
        result: ActResult;
    } | {
        oneofKind: "frame";
        /**
         * @generated from protobuf field: gooey.control.v1.FrameDelta frame = 3
         */
        frame: FrameDelta;
    } | {
        oneofKind: "lifecycle";
        /**
         * @generated from protobuf field: gooey.control.v1.LifecycleEvent lifecycle = 4
         */
        lifecycle: LifecycleEvent;
    } | {
        oneofKind: "input";
        /**
         * @generated from protobuf field: gooey.control.v1.InputEcho input = 5
         */
        input: InputEcho;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Welcome answers the subscribe: who the app is and where its screen
 * stands. Initial state is read through the unary surface (or the
 * first FrameDelta); Welcome deliberately carries identity, not data.
 *
 * @generated from protobuf message gooey.control.v1.Welcome
 */
export interface Welcome {
    /**
     * @generated from protobuf field: string app_name = 1
     */
    appName: string;
    /**
     * @generated from protobuf field: string app_version = 2
     */
    appVersion: string;
    /**
     * @generated from protobuf field: int32 columns = 3
     */
    columns: number;
    /**
     * @generated from protobuf field: int32 rows = 4
     */
    rows: number;
    /**
     * The frame sequence number as of attach; the session's first
     * FrameDelta will carry a number greater than this.
     *
     * @generated from protobuf field: uint64 frame = 5
     */
    frame: bigint;
}
/**
 * ActResult answers one Act. Errors use the same status codes as the
 * unary surface, carried in-stream so one failed act does not tear
 * down the session.
 *
 * @generated from protobuf message gooey.control.v1.ActResult
 */
export interface ActResult {
    /**
     * @generated from protobuf field: uint64 id = 1
     */
    id: bigint;
    /**
     * A google.rpc.Code value; 0 (OK) on success.
     *
     * @generated from protobuf field: uint32 code = 2
     */
    code: number;
    /**
     * Human-readable error, empty on success.
     *
     * @generated from protobuf field: string message = 3
     */
    message: string;
    /**
     * The same response messages the unary surface returns.
     *
     * @generated from protobuf oneof: result
     */
    result: {
        oneofKind: "setProperty";
        /**
         * @generated from protobuf field: gooey.control.v1.SetPropertyResponse set_property = 4
         */
        setProperty: SetPropertyResponse;
    } | {
        oneofKind: "invokeCommand";
        /**
         * @generated from protobuf field: gooey.control.v1.InvokeCommandResponse invoke_command = 5
         */
        invokeCommand: InvokeCommandResponse;
    } | {
        oneofKind: "sendKeys";
        /**
         * @generated from protobuf field: gooey.control.v1.SendKeysResponse send_keys = 6
         */
        sendKeys: SendKeysResponse;
    } | {
        oneofKind: "sendPointer";
        /**
         * @generated from protobuf field: gooey.control.v1.SendPointerResponse send_pointer = 7
         */
        sendPointer: SendPointerResponse;
    } | {
        oneofKind: "setFocus";
        /**
         * @generated from protobuf field: gooey.control.v1.SetFocusResponse set_focus = 8
         */
        setFocus: SetFocusResponse;
    } | {
        oneofKind: "swapMarkup";
        /**
         * @generated from protobuf field: gooey.control.v1.SwapMarkupResponse swap_markup = 9
         */
        swapMarkup: SwapMarkupResponse;
    } | {
        oneofKind: "registerProperties";
        /**
         * @generated from protobuf field: gooey.control.v1.RegisterPropertiesResponse register_properties = 10
         */
        registerProperties: RegisterPropertiesResponse;
    } | {
        oneofKind: undefined;
    };
}
/**
 * FrameDelta is everything one composed frame changed, in one message.
 * Atomic by construction: values and the frame they belong to cannot
 * arrive separately, which is the streaming form of the served-UI
 * rule that markup and values travel as a consistent pair.
 *
 * @generated from protobuf message gooey.control.v1.FrameDelta
 */
export interface FrameDelta {
    /**
     * Monotonically increasing frame sequence number.
     *
     * @generated from protobuf field: uint64 frame = 1
     */
    frame: bigint;
    /**
     * Subscribed properties that changed in this frame, with their
     * settled values.
     *
     * @generated from protobuf field: repeated gooey.control.v1.PropertyChange changes = 2
     */
    changes: PropertyChange[];
    /**
     * Damage rectangles repainted this frame, in cells.
     *
     * @generated from protobuf field: repeated gooey.control.v1.Rect damage = 3
     */
    damage: Rect[];
    /**
     * How many components repainted — the damage-discipline number the
     * framework's contract tests assert on (focus moves repaint 2).
     *
     * @generated from protobuf field: int32 repainted = 4
     */
    repainted: number;
}
/**
 * @generated from protobuf message gooey.control.v1.LifecycleEvent
 */
export interface LifecycleEvent {
    /**
     * @generated from protobuf oneof: event
     */
    event: {
        oneofKind: "resized";
        /**
         * @generated from protobuf field: gooey.control.v1.Resized resized = 1
         */
        resized: Resized;
    } | {
        oneofKind: "swapped";
        /**
         * @generated from protobuf field: gooey.control.v1.Swapped swapped = 2
         */
        swapped: Swapped;
    } | {
        oneofKind: "closing";
        /**
         * @generated from protobuf field: gooey.control.v1.Closing closing = 3
         */
        closing: Closing;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Resized reports the terminal's new size.
 *
 * @generated from protobuf message gooey.control.v1.Resized
 */
export interface Resized {
    /**
     * @generated from protobuf field: int32 columns = 1
     */
    columns: number;
    /**
     * @generated from protobuf field: int32 rows = 2
     */
    rows: number;
}
/**
 * Swapped reports that the page was replaced — by hot reload, by any
 * client's SwapMarkup, or by the app itself. The named table is the
 * new tree's.
 *
 * @generated from protobuf message gooey.control.v1.Swapped
 */
export interface Swapped {
    /**
     * @generated from protobuf field: repeated string named = 1
     */
    named: string[];
}
/**
 * Closing reports that the app is shutting down; the stream ends
 * after this message.
 *
 * @generated from protobuf message gooey.control.v1.Closing
 */
export interface Closing {
}
/**
 * InputEcho is one event from the app's single ordered input stream,
 * echoed to subscribers after dispatch.
 *
 * @generated from protobuf message gooey.control.v1.InputEcho
 */
export interface InputEcho {
    /**
     * @generated from protobuf field: gooey.control.v1.InputEvent event = 1
     */
    event?: InputEvent;
    /**
     * @generated from protobuf field: bool consumed = 2
     */
    consumed: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class AttachRequest$Type extends MessageType<AttachRequest> {
    constructor() {
        super("gooey.control.v1.AttachRequest", [
            { no: 1, name: "subscribe", kind: "message", oneof: "msg", T: () => Subscription },
            { no: 2, name: "act", kind: "message", oneof: "msg", T: () => Act }
        ]);
    }
    create(value?: PartialMessage<AttachRequest>): AttachRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.msg = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<AttachRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AttachRequest): AttachRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.Subscription subscribe */ 1:
                    message.msg = {
                        oneofKind: "subscribe",
                        subscribe: Subscription.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).subscribe)
                    };
                    break;
                case /* gooey.control.v1.Act act */ 2:
                    message.msg = {
                        oneofKind: "act",
                        act: Act.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).act)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AttachRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.Subscription subscribe = 1; */
        if (message.msg.oneofKind === "subscribe")
            Subscription.internalBinaryWrite(message.msg.subscribe, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.Act act = 2; */
        if (message.msg.oneofKind === "act")
            Act.internalBinaryWrite(message.msg.act, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.AttachRequest
 */
export const AttachRequest = new AttachRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Subscription$Type extends MessageType<Subscription> {
    constructor() {
        super("gooey.control.v1.Subscription", [
            { no: 1, name: "properties", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "names", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "frames", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "input", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "lifecycle", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Subscription>): Subscription {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.properties = false;
        message.names = [];
        message.frames = false;
        message.input = false;
        message.lifecycle = false;
        if (value !== undefined)
            reflectionMergePartial<Subscription>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Subscription): Subscription {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool properties */ 1:
                    message.properties = reader.bool();
                    break;
                case /* repeated string names */ 2:
                    message.names.push(reader.string());
                    break;
                case /* bool frames */ 3:
                    message.frames = reader.bool();
                    break;
                case /* bool input */ 4:
                    message.input = reader.bool();
                    break;
                case /* bool lifecycle */ 5:
                    message.lifecycle = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Subscription, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool properties = 1; */
        if (message.properties !== false)
            writer.tag(1, WireType.Varint).bool(message.properties);
        /* repeated string names = 2; */
        for (let i = 0; i < message.names.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.names[i]);
        /* bool frames = 3; */
        if (message.frames !== false)
            writer.tag(3, WireType.Varint).bool(message.frames);
        /* bool input = 4; */
        if (message.input !== false)
            writer.tag(4, WireType.Varint).bool(message.input);
        /* bool lifecycle = 5; */
        if (message.lifecycle !== false)
            writer.tag(5, WireType.Varint).bool(message.lifecycle);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Subscription
 */
export const Subscription = new Subscription$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Act$Type extends MessageType<Act> {
    constructor() {
        super("gooey.control.v1.Act", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "set_property", kind: "message", oneof: "act", T: () => SetPropertyRequest },
            { no: 3, name: "invoke_command", kind: "message", oneof: "act", T: () => InvokeCommandRequest },
            { no: 4, name: "send_keys", kind: "message", oneof: "act", T: () => SendKeysRequest },
            { no: 5, name: "send_pointer", kind: "message", oneof: "act", T: () => SendPointerRequest },
            { no: 6, name: "set_focus", kind: "message", oneof: "act", T: () => SetFocusRequest },
            { no: 7, name: "swap_markup", kind: "message", oneof: "act", T: () => SwapMarkupRequest },
            { no: 8, name: "register_properties", kind: "message", oneof: "act", T: () => RegisterPropertiesRequest }
        ]);
    }
    create(value?: PartialMessage<Act>): Act {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.act = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<Act>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Act): Act {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toBigInt();
                    break;
                case /* gooey.control.v1.SetPropertyRequest set_property */ 2:
                    message.act = {
                        oneofKind: "setProperty",
                        setProperty: SetPropertyRequest.internalBinaryRead(reader, reader.uint32(), options, (message.act as any).setProperty)
                    };
                    break;
                case /* gooey.control.v1.InvokeCommandRequest invoke_command */ 3:
                    message.act = {
                        oneofKind: "invokeCommand",
                        invokeCommand: InvokeCommandRequest.internalBinaryRead(reader, reader.uint32(), options, (message.act as any).invokeCommand)
                    };
                    break;
                case /* gooey.control.v1.SendKeysRequest send_keys */ 4:
                    message.act = {
                        oneofKind: "sendKeys",
                        sendKeys: SendKeysRequest.internalBinaryRead(reader, reader.uint32(), options, (message.act as any).sendKeys)
                    };
                    break;
                case /* gooey.control.v1.SendPointerRequest send_pointer */ 5:
                    message.act = {
                        oneofKind: "sendPointer",
                        sendPointer: SendPointerRequest.internalBinaryRead(reader, reader.uint32(), options, (message.act as any).sendPointer)
                    };
                    break;
                case /* gooey.control.v1.SetFocusRequest set_focus */ 6:
                    message.act = {
                        oneofKind: "setFocus",
                        setFocus: SetFocusRequest.internalBinaryRead(reader, reader.uint32(), options, (message.act as any).setFocus)
                    };
                    break;
                case /* gooey.control.v1.SwapMarkupRequest swap_markup */ 7:
                    message.act = {
                        oneofKind: "swapMarkup",
                        swapMarkup: SwapMarkupRequest.internalBinaryRead(reader, reader.uint32(), options, (message.act as any).swapMarkup)
                    };
                    break;
                case /* gooey.control.v1.RegisterPropertiesRequest register_properties */ 8:
                    message.act = {
                        oneofKind: "registerProperties",
                        registerProperties: RegisterPropertiesRequest.internalBinaryRead(reader, reader.uint32(), options, (message.act as any).registerProperties)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Act, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* gooey.control.v1.SetPropertyRequest set_property = 2; */
        if (message.act.oneofKind === "setProperty")
            SetPropertyRequest.internalBinaryWrite(message.act.setProperty, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.InvokeCommandRequest invoke_command = 3; */
        if (message.act.oneofKind === "invokeCommand")
            InvokeCommandRequest.internalBinaryWrite(message.act.invokeCommand, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SendKeysRequest send_keys = 4; */
        if (message.act.oneofKind === "sendKeys")
            SendKeysRequest.internalBinaryWrite(message.act.sendKeys, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SendPointerRequest send_pointer = 5; */
        if (message.act.oneofKind === "sendPointer")
            SendPointerRequest.internalBinaryWrite(message.act.sendPointer, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SetFocusRequest set_focus = 6; */
        if (message.act.oneofKind === "setFocus")
            SetFocusRequest.internalBinaryWrite(message.act.setFocus, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SwapMarkupRequest swap_markup = 7; */
        if (message.act.oneofKind === "swapMarkup")
            SwapMarkupRequest.internalBinaryWrite(message.act.swapMarkup, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.RegisterPropertiesRequest register_properties = 8; */
        if (message.act.oneofKind === "registerProperties")
            RegisterPropertiesRequest.internalBinaryWrite(message.act.registerProperties, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Act
 */
export const Act = new Act$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AttachResponse$Type extends MessageType<AttachResponse> {
    constructor() {
        super("gooey.control.v1.AttachResponse", [
            { no: 1, name: "welcome", kind: "message", oneof: "msg", T: () => Welcome },
            { no: 2, name: "result", kind: "message", oneof: "msg", T: () => ActResult },
            { no: 3, name: "frame", kind: "message", oneof: "msg", T: () => FrameDelta },
            { no: 4, name: "lifecycle", kind: "message", oneof: "msg", T: () => LifecycleEvent },
            { no: 5, name: "input", kind: "message", oneof: "msg", T: () => InputEcho }
        ]);
    }
    create(value?: PartialMessage<AttachResponse>): AttachResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.msg = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<AttachResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AttachResponse): AttachResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.Welcome welcome */ 1:
                    message.msg = {
                        oneofKind: "welcome",
                        welcome: Welcome.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).welcome)
                    };
                    break;
                case /* gooey.control.v1.ActResult result */ 2:
                    message.msg = {
                        oneofKind: "result",
                        result: ActResult.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).result)
                    };
                    break;
                case /* gooey.control.v1.FrameDelta frame */ 3:
                    message.msg = {
                        oneofKind: "frame",
                        frame: FrameDelta.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).frame)
                    };
                    break;
                case /* gooey.control.v1.LifecycleEvent lifecycle */ 4:
                    message.msg = {
                        oneofKind: "lifecycle",
                        lifecycle: LifecycleEvent.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).lifecycle)
                    };
                    break;
                case /* gooey.control.v1.InputEcho input */ 5:
                    message.msg = {
                        oneofKind: "input",
                        input: InputEcho.internalBinaryRead(reader, reader.uint32(), options, (message.msg as any).input)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AttachResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.Welcome welcome = 1; */
        if (message.msg.oneofKind === "welcome")
            Welcome.internalBinaryWrite(message.msg.welcome, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.ActResult result = 2; */
        if (message.msg.oneofKind === "result")
            ActResult.internalBinaryWrite(message.msg.result, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.FrameDelta frame = 3; */
        if (message.msg.oneofKind === "frame")
            FrameDelta.internalBinaryWrite(message.msg.frame, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.LifecycleEvent lifecycle = 4; */
        if (message.msg.oneofKind === "lifecycle")
            LifecycleEvent.internalBinaryWrite(message.msg.lifecycle, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.InputEcho input = 5; */
        if (message.msg.oneofKind === "input")
            InputEcho.internalBinaryWrite(message.msg.input, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.AttachResponse
 */
export const AttachResponse = new AttachResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Welcome$Type extends MessageType<Welcome> {
    constructor() {
        super("gooey.control.v1.Welcome", [
            { no: 1, name: "app_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "app_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "columns", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "rows", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "frame", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<Welcome>): Welcome {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.appName = "";
        message.appVersion = "";
        message.columns = 0;
        message.rows = 0;
        message.frame = 0n;
        if (value !== undefined)
            reflectionMergePartial<Welcome>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Welcome): Welcome {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string app_name */ 1:
                    message.appName = reader.string();
                    break;
                case /* string app_version */ 2:
                    message.appVersion = reader.string();
                    break;
                case /* int32 columns */ 3:
                    message.columns = reader.int32();
                    break;
                case /* int32 rows */ 4:
                    message.rows = reader.int32();
                    break;
                case /* uint64 frame */ 5:
                    message.frame = reader.uint64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Welcome, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string app_name = 1; */
        if (message.appName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.appName);
        /* string app_version = 2; */
        if (message.appVersion !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.appVersion);
        /* int32 columns = 3; */
        if (message.columns !== 0)
            writer.tag(3, WireType.Varint).int32(message.columns);
        /* int32 rows = 4; */
        if (message.rows !== 0)
            writer.tag(4, WireType.Varint).int32(message.rows);
        /* uint64 frame = 5; */
        if (message.frame !== 0n)
            writer.tag(5, WireType.Varint).uint64(message.frame);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Welcome
 */
export const Welcome = new Welcome$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ActResult$Type extends MessageType<ActResult> {
    constructor() {
        super("gooey.control.v1.ActResult", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "code", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "set_property", kind: "message", oneof: "result", T: () => SetPropertyResponse },
            { no: 5, name: "invoke_command", kind: "message", oneof: "result", T: () => InvokeCommandResponse },
            { no: 6, name: "send_keys", kind: "message", oneof: "result", T: () => SendKeysResponse },
            { no: 7, name: "send_pointer", kind: "message", oneof: "result", T: () => SendPointerResponse },
            { no: 8, name: "set_focus", kind: "message", oneof: "result", T: () => SetFocusResponse },
            { no: 9, name: "swap_markup", kind: "message", oneof: "result", T: () => SwapMarkupResponse },
            { no: 10, name: "register_properties", kind: "message", oneof: "result", T: () => RegisterPropertiesResponse }
        ]);
    }
    create(value?: PartialMessage<ActResult>): ActResult {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.code = 0;
        message.message = "";
        message.result = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<ActResult>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ActResult): ActResult {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toBigInt();
                    break;
                case /* uint32 code */ 2:
                    message.code = reader.uint32();
                    break;
                case /* string message */ 3:
                    message.message = reader.string();
                    break;
                case /* gooey.control.v1.SetPropertyResponse set_property */ 4:
                    message.result = {
                        oneofKind: "setProperty",
                        setProperty: SetPropertyResponse.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).setProperty)
                    };
                    break;
                case /* gooey.control.v1.InvokeCommandResponse invoke_command */ 5:
                    message.result = {
                        oneofKind: "invokeCommand",
                        invokeCommand: InvokeCommandResponse.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).invokeCommand)
                    };
                    break;
                case /* gooey.control.v1.SendKeysResponse send_keys */ 6:
                    message.result = {
                        oneofKind: "sendKeys",
                        sendKeys: SendKeysResponse.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).sendKeys)
                    };
                    break;
                case /* gooey.control.v1.SendPointerResponse send_pointer */ 7:
                    message.result = {
                        oneofKind: "sendPointer",
                        sendPointer: SendPointerResponse.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).sendPointer)
                    };
                    break;
                case /* gooey.control.v1.SetFocusResponse set_focus */ 8:
                    message.result = {
                        oneofKind: "setFocus",
                        setFocus: SetFocusResponse.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).setFocus)
                    };
                    break;
                case /* gooey.control.v1.SwapMarkupResponse swap_markup */ 9:
                    message.result = {
                        oneofKind: "swapMarkup",
                        swapMarkup: SwapMarkupResponse.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).swapMarkup)
                    };
                    break;
                case /* gooey.control.v1.RegisterPropertiesResponse register_properties */ 10:
                    message.result = {
                        oneofKind: "registerProperties",
                        registerProperties: RegisterPropertiesResponse.internalBinaryRead(reader, reader.uint32(), options, (message.result as any).registerProperties)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ActResult, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* uint32 code = 2; */
        if (message.code !== 0)
            writer.tag(2, WireType.Varint).uint32(message.code);
        /* string message = 3; */
        if (message.message !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.message);
        /* gooey.control.v1.SetPropertyResponse set_property = 4; */
        if (message.result.oneofKind === "setProperty")
            SetPropertyResponse.internalBinaryWrite(message.result.setProperty, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.InvokeCommandResponse invoke_command = 5; */
        if (message.result.oneofKind === "invokeCommand")
            InvokeCommandResponse.internalBinaryWrite(message.result.invokeCommand, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SendKeysResponse send_keys = 6; */
        if (message.result.oneofKind === "sendKeys")
            SendKeysResponse.internalBinaryWrite(message.result.sendKeys, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SendPointerResponse send_pointer = 7; */
        if (message.result.oneofKind === "sendPointer")
            SendPointerResponse.internalBinaryWrite(message.result.sendPointer, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SetFocusResponse set_focus = 8; */
        if (message.result.oneofKind === "setFocus")
            SetFocusResponse.internalBinaryWrite(message.result.setFocus, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.SwapMarkupResponse swap_markup = 9; */
        if (message.result.oneofKind === "swapMarkup")
            SwapMarkupResponse.internalBinaryWrite(message.result.swapMarkup, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.RegisterPropertiesResponse register_properties = 10; */
        if (message.result.oneofKind === "registerProperties")
            RegisterPropertiesResponse.internalBinaryWrite(message.result.registerProperties, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ActResult
 */
export const ActResult = new ActResult$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FrameDelta$Type extends MessageType<FrameDelta> {
    constructor() {
        super("gooey.control.v1.FrameDelta", [
            { no: 1, name: "frame", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "changes", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PropertyChange },
            { no: 3, name: "damage", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Rect },
            { no: 4, name: "repainted", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<FrameDelta>): FrameDelta {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.frame = 0n;
        message.changes = [];
        message.damage = [];
        message.repainted = 0;
        if (value !== undefined)
            reflectionMergePartial<FrameDelta>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FrameDelta): FrameDelta {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 frame */ 1:
                    message.frame = reader.uint64().toBigInt();
                    break;
                case /* repeated gooey.control.v1.PropertyChange changes */ 2:
                    message.changes.push(PropertyChange.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated gooey.control.v1.Rect damage */ 3:
                    message.damage.push(Rect.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 repainted */ 4:
                    message.repainted = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FrameDelta, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 frame = 1; */
        if (message.frame !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.frame);
        /* repeated gooey.control.v1.PropertyChange changes = 2; */
        for (let i = 0; i < message.changes.length; i++)
            PropertyChange.internalBinaryWrite(message.changes[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated gooey.control.v1.Rect damage = 3; */
        for (let i = 0; i < message.damage.length; i++)
            Rect.internalBinaryWrite(message.damage[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* int32 repainted = 4; */
        if (message.repainted !== 0)
            writer.tag(4, WireType.Varint).int32(message.repainted);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.FrameDelta
 */
export const FrameDelta = new FrameDelta$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LifecycleEvent$Type extends MessageType<LifecycleEvent> {
    constructor() {
        super("gooey.control.v1.LifecycleEvent", [
            { no: 1, name: "resized", kind: "message", oneof: "event", T: () => Resized },
            { no: 2, name: "swapped", kind: "message", oneof: "event", T: () => Swapped },
            { no: 3, name: "closing", kind: "message", oneof: "event", T: () => Closing }
        ]);
    }
    create(value?: PartialMessage<LifecycleEvent>): LifecycleEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.event = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<LifecycleEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LifecycleEvent): LifecycleEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.Resized resized */ 1:
                    message.event = {
                        oneofKind: "resized",
                        resized: Resized.internalBinaryRead(reader, reader.uint32(), options, (message.event as any).resized)
                    };
                    break;
                case /* gooey.control.v1.Swapped swapped */ 2:
                    message.event = {
                        oneofKind: "swapped",
                        swapped: Swapped.internalBinaryRead(reader, reader.uint32(), options, (message.event as any).swapped)
                    };
                    break;
                case /* gooey.control.v1.Closing closing */ 3:
                    message.event = {
                        oneofKind: "closing",
                        closing: Closing.internalBinaryRead(reader, reader.uint32(), options, (message.event as any).closing)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LifecycleEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.Resized resized = 1; */
        if (message.event.oneofKind === "resized")
            Resized.internalBinaryWrite(message.event.resized, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.Swapped swapped = 2; */
        if (message.event.oneofKind === "swapped")
            Swapped.internalBinaryWrite(message.event.swapped, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.Closing closing = 3; */
        if (message.event.oneofKind === "closing")
            Closing.internalBinaryWrite(message.event.closing, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.LifecycleEvent
 */
export const LifecycleEvent = new LifecycleEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Resized$Type extends MessageType<Resized> {
    constructor() {
        super("gooey.control.v1.Resized", [
            { no: 1, name: "columns", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "rows", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Resized>): Resized {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.columns = 0;
        message.rows = 0;
        if (value !== undefined)
            reflectionMergePartial<Resized>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Resized): Resized {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 columns */ 1:
                    message.columns = reader.int32();
                    break;
                case /* int32 rows */ 2:
                    message.rows = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Resized, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 columns = 1; */
        if (message.columns !== 0)
            writer.tag(1, WireType.Varint).int32(message.columns);
        /* int32 rows = 2; */
        if (message.rows !== 0)
            writer.tag(2, WireType.Varint).int32(message.rows);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Resized
 */
export const Resized = new Resized$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Swapped$Type extends MessageType<Swapped> {
    constructor() {
        super("gooey.control.v1.Swapped", [
            { no: 1, name: "named", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Swapped>): Swapped {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.named = [];
        if (value !== undefined)
            reflectionMergePartial<Swapped>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Swapped): Swapped {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string named */ 1:
                    message.named.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Swapped, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string named = 1; */
        for (let i = 0; i < message.named.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.named[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Swapped
 */
export const Swapped = new Swapped$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Closing$Type extends MessageType<Closing> {
    constructor() {
        super("gooey.control.v1.Closing", []);
    }
    create(value?: PartialMessage<Closing>): Closing {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<Closing>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Closing): Closing {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Closing, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Closing
 */
export const Closing = new Closing$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InputEcho$Type extends MessageType<InputEcho> {
    constructor() {
        super("gooey.control.v1.InputEcho", [
            { no: 1, name: "event", kind: "message", T: () => InputEvent },
            { no: 2, name: "consumed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<InputEcho>): InputEcho {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.consumed = false;
        if (value !== undefined)
            reflectionMergePartial<InputEcho>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InputEcho): InputEcho {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.InputEvent event */ 1:
                    message.event = InputEvent.internalBinaryRead(reader, reader.uint32(), options, message.event);
                    break;
                case /* bool consumed */ 2:
                    message.consumed = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InputEcho, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.InputEvent event = 1; */
        if (message.event)
            InputEvent.internalBinaryWrite(message.event, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool consumed = 2; */
        if (message.consumed !== false)
            writer.tag(2, WireType.Varint).bool(message.consumed);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.InputEcho
 */
export const InputEcho = new InputEcho$Type();
/**
 * @generated ServiceType for protobuf service gooey.control.v1.SessionService
 */
export const SessionService = new ServiceType("gooey.control.v1.SessionService", [
    { name: "Attach", serverStreaming: true, clientStreaming: true, options: {}, I: AttachRequest, O: AttachResponse }
]);
