// @generated by protobuf-ts 2.11.1 with parameter client_grpc1
// @generated from protobuf file "gooey/control/v1/types.proto" (package "gooey.control.v1", syntax proto3)
// tslint:disable
//
// gooey.control.v1 — the one model.
//
// This package is the wire contract for controlling a running gooey app:
// the surface the MCP server, the server-driven UI layer, and every
// generated client (Go/Python/TypeScript) share. One path, one model —
// no parallel data models (issue #108).
//
// The type system here MIRRORS markup's propKinds table
// (markup/property.go). It does not extend it: adding a value kind to
// the wire means adding a row to propKinds first, then the matching
// oneof case here. Anything a *prop.Property[T] can hold that is NOT on
// that table (render.Style, []float64) crosses only as a descriptor
// (ValueInfo.go_type), never as a TypedValue.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Duration } from "../../../google/protobuf/duration";
/**
 * TypedValue carries one value of a propKinds type. The oneof is the
 * wire form of the type-switch every boundary in gooey already does:
 * exactly one case per table row, no reflection, no stringly escape
 * except the deliberate `any` row.
 *
 * @generated from protobuf message gooey.control.v1.TypedValue
 */
export interface TypedValue {
    /**
     * @generated from protobuf oneof: kind
     */
    kind: {
        oneofKind: "stringValue";
        /**
         * @generated from protobuf field: string string_value = 1
         */
        stringValue: string;
    } | {
        oneofKind: "intValue";
        /**
         * Go int, carried wide. Servers reject values outside the host's
         * int range with INVALID_ARGUMENT.
         *
         * @generated from protobuf field: sint64 int_value = 2
         */
        intValue: bigint;
    } | {
        oneofKind: "boolValue";
        /**
         * @generated from protobuf field: bool bool_value = 3
         */
        boolValue: boolean;
    } | {
        oneofKind: "floatValue";
        /**
         * @generated from protobuf field: double float_value = 4
         */
        floatValue: number;
    } | {
        oneofKind: "durationValue";
        /**
         * @generated from protobuf field: google.protobuf.Duration duration_value = 5
         */
        durationValue: Duration;
    } | {
        oneofKind: "colorValue";
        /**
         * @generated from protobuf field: gooey.control.v1.Color color_value = 6
         */
        colorValue: Color;
    } | {
        oneofKind: "anyJson";
        /**
         * UTF-8 JSON document — the wire spelling of propKinds' `any`.
         *
         * @generated from protobuf field: bytes any_json = 7
         */
        anyJson: Uint8Array;
    } | {
        oneofKind: undefined;
    };
}
/**
 * Color mirrors render.Color, including its Set flag: a terminal color
 * is either an explicit RGB or "unset, use the terminal default", and
 * all-zero RGB (black) must stay distinguishable from unset.
 *
 * @generated from protobuf message gooey.control.v1.Color
 */
export interface Color {
    /**
     * @generated from protobuf field: bool set = 1
     */
    set: boolean;
    /**
     * @generated from protobuf field: uint32 red = 2
     */
    red: number;
    /**
     * @generated from protobuf field: uint32 green = 3
     */
    green: number;
    /**
     * @generated from protobuf field: uint32 blue = 4
     */
    blue: number;
}
/**
 * PropertyDeclaration is one <x:Property> — the wire form of
 * markup.Declaration, carried verbatim: the declaration block IS the
 * per-control schema (issue #62).
 *
 * @generated from protobuf message gooey.control.v1.PropertyDeclaration
 */
export interface PropertyDeclaration {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.ValueKind type = 2
     */
    type: ValueKind;
    /**
     * The default as the markup literal it was declared with, coerced by
     * `type` using the same table the loader uses. Empty means the
     * type's zero value (and is meaningless when required is true —
     * Required and Default are exclusive at declaration time).
     *
     * @generated from protobuf field: string default_literal = 3
     */
    defaultLiteral: string;
    /**
     * @generated from protobuf field: bool required = 4
     */
    required: boolean;
}
/**
 * ControlSchema is a control file's declared surface: what a payload
 * must supply before the document can build.
 *
 * @generated from protobuf message gooey.control.v1.ControlSchema
 */
export interface ControlSchema {
    /**
     * The control's identity — its markup file name where known,
     * otherwise empty for an anonymous document.
     *
     * @generated from protobuf field: string control = 1
     */
    control: string;
    /**
     * @generated from protobuf field: repeated gooey.control.v1.PropertyDeclaration properties = 2
     */
    properties: PropertyDeclaration[];
}
/**
 * PropertyRegistration asks the server to materialize a fresh typed
 * source property in the app's binding context before a markup build
 * (issue #89). Commands cannot be registered — behavior needs code,
 * not storage; that boundary is the app's.
 *
 * @generated from protobuf message gooey.control.v1.PropertyRegistration
 */
export interface PropertyRegistration {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.ValueKind kind = 2
     */
    kind: ValueKind;
    /**
     * Optional initial value; absent means the kind's zero value. Must
     * match `kind` or the registration is rejected.
     *
     * @generated from protobuf field: gooey.control.v1.TypedValue initial = 3
     */
    initial?: TypedValue;
}
/**
 * ValueInfo describes one dotted name in the binding context.
 *
 * @generated from protobuf message gooey.control.v1.ValueInfo
 */
export interface ValueInfo {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.EntryKind kind = 2
     */
    kind: EntryKind;
    /**
     * The propKinds row, when the entry is a property on the table;
     * VALUE_KIND_UNSPECIFIED for off-table handles (style, float
     * slices), commands and literals.
     *
     * @generated from protobuf field: gooey.control.v1.ValueKind type = 3
     */
    type: ValueKind;
    /**
     * The current value, when it is representable as a TypedValue.
     *
     * @generated from protobuf field: gooey.control.v1.TypedValue value = 4
     */
    value?: TypedValue;
    /**
     * The Go type (%T), diagnostic only — never parse it.
     *
     * @generated from protobuf field: string go_type = 5
     */
    goType: string;
}
/**
 * PropertyChange is one property delta: this name now has this value.
 *
 * @generated from protobuf message gooey.control.v1.PropertyChange
 */
export interface PropertyChange {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.TypedValue value = 2
     */
    value?: TypedValue;
}
/**
 * Rect is a cell-space rectangle: terminal columns and rows, 0-based.
 *
 * @generated from protobuf message gooey.control.v1.Rect
 */
export interface Rect {
    /**
     * @generated from protobuf field: int32 x = 1
     */
    x: number;
    /**
     * @generated from protobuf field: int32 y = 2
     */
    y: number;
    /**
     * @generated from protobuf field: int32 width = 3
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 4
     */
    height: number;
}
/**
 * Margin is a Thickness: left, top, right, bottom, in cells.
 *
 * @generated from protobuf message gooey.control.v1.Margin
 */
export interface Margin {
    /**
     * @generated from protobuf field: int32 left = 1
     */
    left: number;
    /**
     * @generated from protobuf field: int32 top = 2
     */
    top: number;
    /**
     * @generated from protobuf field: int32 right = 3
     */
    right: number;
    /**
     * @generated from protobuf field: int32 bottom = 4
     */
    bottom: number;
}
/**
 * Layout is the FrameworkElement surface of a node — gooey.Layout as
 * arranged. proto3 zero values coincide with the framework defaults,
 * so an omitted field reads exactly like the snapshot's
 * "only what was set" convention.
 *
 * @generated from protobuf message gooey.control.v1.Layout
 */
export interface Layout {
    /**
     * @generated from protobuf field: int32 width = 1
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 2
     */
    height: number;
    /**
     * @generated from protobuf field: gooey.control.v1.Margin margin = 3
     */
    margin?: Margin;
    /**
     * @generated from protobuf field: gooey.control.v1.Align h_align = 4
     */
    hAlign: Align;
    /**
     * @generated from protobuf field: gooey.control.v1.Align v_align = 5
     */
    vAlign: Align;
    /**
     * @generated from protobuf field: gooey.control.v1.Visibility visibility = 6
     */
    visibility: Visibility;
    /**
     * @generated from protobuf field: int32 grid_row = 7
     */
    gridRow: number;
    /**
     * @generated from protobuf field: int32 grid_col = 8
     */
    gridCol: number;
    /**
     * @generated from protobuf field: int32 grid_row_span = 9
     */
    gridRowSpan: number;
    /**
     * @generated from protobuf field: int32 grid_col_span = 10
     */
    gridColSpan: number;
    /**
     * @generated from protobuf field: int32 canvas_left = 11
     */
    canvasLeft: number;
    /**
     * @generated from protobuf field: int32 canvas_top = 12
     */
    canvasTop: number;
}
/**
 * TreeNode is one component in the live tree, as the MCP tree_snapshot
 * serializes it today: identity, geometry, layout, focus state, and
 * the type-switched interesting properties of known component kinds.
 *
 * @generated from protobuf message gooey.control.v1.TreeNode
 */
export interface TreeNode {
    /**
     * The Go type, e.g. "*components.Button". Diagnostic identity; the
     * durable identity is `name`.
     *
     * @generated from protobuf field: string type = 1
     */
    type: string;
    /**
     * The Name= identity from markup, empty if unnamed.
     *
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.Rect bounds = 3
     */
    bounds?: Rect;
    /**
     * @generated from protobuf field: gooey.control.v1.Layout layout = 4
     */
    layout?: Layout;
    /**
     * @generated from protobuf field: bool focusable = 5
     */
    focusable: boolean;
    /**
     * @generated from protobuf field: bool focused = 6
     */
    focused: boolean;
    /**
     * @generated from protobuf field: bool hovered = 7
     */
    hovered: boolean;
    /**
     * The type-switched per-component fields (text, checked, caret, …).
     * Values use the same TypedValue table as everything else.
     *
     * @generated from protobuf field: map<string, gooey.control.v1.TypedValue> props = 8
     */
    props: {
        [key: string]: TypedValue;
    };
    /**
     * Non-visual attachments (KeyBindings, Timers).
     *
     * @generated from protobuf field: repeated gooey.control.v1.TreeNode attached = 9
     */
    attached: TreeNode[];
    /**
     * @generated from protobuf field: repeated gooey.control.v1.TreeNode children = 10
     */
    children: TreeNode[];
    /**
     * When a depth limit elided this node's children, how many there were.
     *
     * @generated from protobuf field: int32 children_elided = 11
     */
    childrenElided: number;
    /**
     * The markup-declared (<x:Property>) property surface of the control
     * instance rooted at this node, with current values (issue #117).
     * Present only on control roots that declare; an arbitrary Go
     * component's ceiling remains the %T in `type` — its fields cannot be
     * discovered without reflection, and stay undiscovered. Declared
     * surfaces serialize; undeclared Go structs never will.
     *
     * @generated from protobuf field: repeated gooey.control.v1.DeclaredValue declared = 16
     */
    declared: DeclaredValue[];
    /**
     * The control file the declarations came from, e.g. "card.gooey".
     *
     * @generated from protobuf field: string control = 17
     */
    control: string;
}
/**
 * DeclaredValue is one markup-declared dependency property
 * (<x:Property>) as a tree snapshot reports it: the declaration's name
 * and kind plus the instance's CURRENT value — where PropertyDeclaration
 * carries the declared default, this carries what the running instance
 * holds now.
 *
 * @generated from protobuf message gooey.control.v1.DeclaredValue
 */
export interface DeclaredValue {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.ValueKind type = 2
     */
    type: ValueKind;
    /**
     * The current value, for kinds TypedValue carries. Absent for
     * VALUE_KIND_ANY handles, whose ceiling is the descriptor.
     *
     * @generated from protobuf field: gooey.control.v1.TypedValue value = 3
     */
    value?: TypedValue;
    /**
     * For off-table handles (VALUE_KIND_ANY): the Go type (%T) of what
     * the handle holds. Diagnostic only — never parse it.
     *
     * @generated from protobuf field: string go_type = 4
     */
    goType: string;
}
/**
 * StyleInfo is one named entry in the markup context's style table —
 * what a Style="name" attribute can resolve. An unknown style name in
 * markup silently renders unstyled, so a markup generator needs this
 * table. Mirrors render.Style; colors carry their Set flag, so an unset
 * attribute stays distinguishable from black.
 *
 * @generated from protobuf message gooey.control.v1.StyleInfo
 */
export interface StyleInfo {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: gooey.control.v1.Color fg = 2
     */
    fg?: Color;
    /**
     * @generated from protobuf field: gooey.control.v1.Color bg = 3
     */
    bg?: Color;
    /**
     * @generated from protobuf field: bool bold = 4
     */
    bold: boolean;
    /**
     * @generated from protobuf field: bool dim = 5
     */
    dim: boolean;
    /**
     * @generated from protobuf field: bool underline = 6
     */
    underline: boolean;
    /**
     * @generated from protobuf field: bool reverse = 7
     */
    reverse: boolean;
}
/**
 * PointerEvent is one pointer action at a cell coordinate.
 *
 * @generated from protobuf message gooey.control.v1.PointerEvent
 */
export interface PointerEvent {
    /**
     * @generated from protobuf field: gooey.control.v1.PointerKind kind = 1
     */
    kind: PointerKind;
    /**
     * @generated from protobuf field: int32 x = 2
     */
    x: number;
    /**
     * @generated from protobuf field: int32 y = 3
     */
    y: number;
    /**
     * @generated from protobuf field: gooey.control.v1.MouseButton button = 4
     */
    button: MouseButton;
}
/**
 * KeyEvent is one key gesture in markup's gesture syntax — "ctrl+s",
 * "tab", "shift+tab", "j". One spelling everywhere: the same strings
 * input.ParseGesture reads and KeyEvent.String writes.
 *
 * @generated from protobuf message gooey.control.v1.KeyEvent
 */
export interface KeyEvent {
    /**
     * @generated from protobuf field: string gesture = 1
     */
    gesture: string;
}
/**
 * InputEvent is one event on the app's single ordered input stream —
 * keys and pointer interleaved, exactly as input.Event interleaves
 * them.
 *
 * @generated from protobuf message gooey.control.v1.InputEvent
 */
export interface InputEvent {
    /**
     * @generated from protobuf oneof: event
     */
    event: {
        oneofKind: "key";
        /**
         * @generated from protobuf field: gooey.control.v1.KeyEvent key = 1
         */
        key: KeyEvent;
    } | {
        oneofKind: "pointer";
        /**
         * @generated from protobuf field: gooey.control.v1.PointerEvent pointer = 2
         */
        pointer: PointerEvent;
    } | {
        oneofKind: undefined;
    };
}
/**
 * ValueKind names one row of markup's propKinds table. It is used
 * wherever a type is DESCRIBED rather than carried: property schemas
 * (x:Property declarations, issue #62) and runtime registrations
 * (issue #89).
 *
 * @generated from protobuf enum gooey.control.v1.ValueKind
 */
export enum ValueKind {
    /**
     * @generated from protobuf enum value: VALUE_KIND_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: VALUE_KIND_STRING = 1;
     */
    STRING = 1,
    /**
     * @generated from protobuf enum value: VALUE_KIND_INT = 2;
     */
    INT = 2,
    /**
     * @generated from protobuf enum value: VALUE_KIND_BOOL = 3;
     */
    BOOL = 3,
    /**
     * @generated from protobuf enum value: VALUE_KIND_FLOAT = 4;
     */
    FLOAT = 4,
    /**
     * @generated from protobuf enum value: VALUE_KIND_DURATION = 5;
     */
    DURATION = 5,
    /**
     * @generated from protobuf enum value: VALUE_KIND_COLOR = 6;
     */
    COLOR = 6,
    /**
     * The escape hatch for app types with no markup literal, exactly as
     * in propKinds. On the wire an `any` value is UTF-8 JSON bytes
     * (TypedValue.any_json).
     *
     * 8–15 are earmarked (not reserved) for future propKinds rows, so
     * ValueKind and the TypedValue oneof can grow in lockstep.
     *
     * @generated from protobuf enum value: VALUE_KIND_ANY = 7;
     */
    ANY = 7
}
/**
 * EntryKind classifies one name in the binding context, matching the
 * MCP list_values categories.
 *
 * @generated from protobuf enum gooey.control.v1.EntryKind
 */
export enum EntryKind {
    /**
     * @generated from protobuf enum value: ENTRY_KIND_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ENTRY_KIND_PROPERTY = 1;
     */
    PROPERTY = 1,
    /**
     * @generated from protobuf enum value: ENTRY_KIND_COMMAND = 2;
     */
    COMMAND = 2,
    /**
     * @generated from protobuf enum value: ENTRY_KIND_LITERAL = 3;
     */
    LITERAL = 3,
    /**
     * A context entry that is none of the above — present and
     * addressable but not typed by the table.
     *
     * @generated from protobuf enum value: ENTRY_KIND_OTHER = 4;
     */
    OTHER = 4
}
/**
 * Align mirrors gooey.Align. The zero value means the framework
 * default, Stretch — matching the tree snapshot's convention of
 * reporting only what was explicitly set.
 *
 * @generated from protobuf enum gooey.control.v1.Align
 */
export enum Align {
    /**
     * @generated from protobuf enum value: ALIGN_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ALIGN_START = 1;
     */
    START = 1,
    /**
     * @generated from protobuf enum value: ALIGN_CENTER = 2;
     */
    CENTER = 2,
    /**
     * @generated from protobuf enum value: ALIGN_END = 3;
     */
    END = 3
}
/**
 * Visibility mirrors gooey.Visibility; the zero value means Visible.
 *
 * @generated from protobuf enum gooey.control.v1.Visibility
 */
export enum Visibility {
    /**
     * @generated from protobuf enum value: VISIBILITY_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: VISIBILITY_HIDDEN = 1;
     */
    HIDDEN = 1,
    /**
     * @generated from protobuf enum value: VISIBILITY_COLLAPSED = 2;
     */
    COLLAPSED = 2
}
/**
 * PointerKind mirrors the MCP send_mouse kinds. CLICK is synthesized
 * server-side as press+release on the same cell, exactly as a terminal
 * dispatcher does — a terminal never sends a click.
 *
 * @generated from protobuf enum gooey.control.v1.PointerKind
 */
export enum PointerKind {
    /**
     * @generated from protobuf enum value: POINTER_KIND_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: POINTER_KIND_CLICK = 1;
     */
    CLICK = 1,
    /**
     * @generated from protobuf enum value: POINTER_KIND_PRESS = 2;
     */
    PRESS = 2,
    /**
     * @generated from protobuf enum value: POINTER_KIND_RELEASE = 3;
     */
    RELEASE = 3,
    /**
     * @generated from protobuf enum value: POINTER_KIND_MOVE = 4;
     */
    MOVE = 4,
    /**
     * @generated from protobuf enum value: POINTER_KIND_WHEEL_UP = 5;
     */
    WHEEL_UP = 5,
    /**
     * @generated from protobuf enum value: POINTER_KIND_WHEEL_DOWN = 6;
     */
    WHEEL_DOWN = 6
}
/**
 * MouseButton mirrors input.MouseButton. UNSPECIFIED means left, the
 * MCP default, so the common case needs no field.
 *
 * @generated from protobuf enum gooey.control.v1.MouseButton
 */
export enum MouseButton {
    /**
     * @generated from protobuf enum value: MOUSE_BUTTON_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: MOUSE_BUTTON_LEFT = 1;
     */
    LEFT = 1,
    /**
     * @generated from protobuf enum value: MOUSE_BUTTON_MIDDLE = 2;
     */
    MIDDLE = 2,
    /**
     * @generated from protobuf enum value: MOUSE_BUTTON_RIGHT = 3;
     */
    RIGHT = 3,
    /**
     * @generated from protobuf enum value: MOUSE_BUTTON_NONE = 4;
     */
    NONE = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class TypedValue$Type extends MessageType<TypedValue> {
    constructor() {
        super("gooey.control.v1.TypedValue", [
            { no: 1, name: "string_value", kind: "scalar", oneof: "kind", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "int_value", kind: "scalar", oneof: "kind", T: 18 /*ScalarType.SINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "bool_value", kind: "scalar", oneof: "kind", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "float_value", kind: "scalar", oneof: "kind", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "duration_value", kind: "message", oneof: "kind", T: () => Duration },
            { no: 6, name: "color_value", kind: "message", oneof: "kind", T: () => Color },
            { no: 7, name: "any_json", kind: "scalar", oneof: "kind", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<TypedValue>): TypedValue {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<TypedValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TypedValue): TypedValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string string_value */ 1:
                    message.kind = {
                        oneofKind: "stringValue",
                        stringValue: reader.string()
                    };
                    break;
                case /* sint64 int_value */ 2:
                    message.kind = {
                        oneofKind: "intValue",
                        intValue: reader.sint64().toBigInt()
                    };
                    break;
                case /* bool bool_value */ 3:
                    message.kind = {
                        oneofKind: "boolValue",
                        boolValue: reader.bool()
                    };
                    break;
                case /* double float_value */ 4:
                    message.kind = {
                        oneofKind: "floatValue",
                        floatValue: reader.double()
                    };
                    break;
                case /* google.protobuf.Duration duration_value */ 5:
                    message.kind = {
                        oneofKind: "durationValue",
                        durationValue: Duration.internalBinaryRead(reader, reader.uint32(), options, (message.kind as any).durationValue)
                    };
                    break;
                case /* gooey.control.v1.Color color_value */ 6:
                    message.kind = {
                        oneofKind: "colorValue",
                        colorValue: Color.internalBinaryRead(reader, reader.uint32(), options, (message.kind as any).colorValue)
                    };
                    break;
                case /* bytes any_json */ 7:
                    message.kind = {
                        oneofKind: "anyJson",
                        anyJson: reader.bytes()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TypedValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string string_value = 1; */
        if (message.kind.oneofKind === "stringValue")
            writer.tag(1, WireType.LengthDelimited).string(message.kind.stringValue);
        /* sint64 int_value = 2; */
        if (message.kind.oneofKind === "intValue")
            writer.tag(2, WireType.Varint).sint64(message.kind.intValue);
        /* bool bool_value = 3; */
        if (message.kind.oneofKind === "boolValue")
            writer.tag(3, WireType.Varint).bool(message.kind.boolValue);
        /* double float_value = 4; */
        if (message.kind.oneofKind === "floatValue")
            writer.tag(4, WireType.Bit64).double(message.kind.floatValue);
        /* google.protobuf.Duration duration_value = 5; */
        if (message.kind.oneofKind === "durationValue")
            Duration.internalBinaryWrite(message.kind.durationValue, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.Color color_value = 6; */
        if (message.kind.oneofKind === "colorValue")
            Color.internalBinaryWrite(message.kind.colorValue, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* bytes any_json = 7; */
        if (message.kind.oneofKind === "anyJson")
            writer.tag(7, WireType.LengthDelimited).bytes(message.kind.anyJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.TypedValue
 */
export const TypedValue = new TypedValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Color$Type extends MessageType<Color> {
    constructor() {
        super("gooey.control.v1.Color", [
            { no: 1, name: "set", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "red", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "green", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "blue", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<Color>): Color {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.set = false;
        message.red = 0;
        message.green = 0;
        message.blue = 0;
        if (value !== undefined)
            reflectionMergePartial<Color>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Color): Color {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool set */ 1:
                    message.set = reader.bool();
                    break;
                case /* uint32 red */ 2:
                    message.red = reader.uint32();
                    break;
                case /* uint32 green */ 3:
                    message.green = reader.uint32();
                    break;
                case /* uint32 blue */ 4:
                    message.blue = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Color, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool set = 1; */
        if (message.set !== false)
            writer.tag(1, WireType.Varint).bool(message.set);
        /* uint32 red = 2; */
        if (message.red !== 0)
            writer.tag(2, WireType.Varint).uint32(message.red);
        /* uint32 green = 3; */
        if (message.green !== 0)
            writer.tag(3, WireType.Varint).uint32(message.green);
        /* uint32 blue = 4; */
        if (message.blue !== 0)
            writer.tag(4, WireType.Varint).uint32(message.blue);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Color
 */
export const Color = new Color$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyDeclaration$Type extends MessageType<PropertyDeclaration> {
    constructor() {
        super("gooey.control.v1.PropertyDeclaration", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["gooey.control.v1.ValueKind", ValueKind, "VALUE_KIND_"] },
            { no: 3, name: "default_literal", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "required", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PropertyDeclaration>): PropertyDeclaration {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.type = 0;
        message.defaultLiteral = "";
        message.required = false;
        if (value !== undefined)
            reflectionMergePartial<PropertyDeclaration>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PropertyDeclaration): PropertyDeclaration {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.ValueKind type */ 2:
                    message.type = reader.int32();
                    break;
                case /* string default_literal */ 3:
                    message.defaultLiteral = reader.string();
                    break;
                case /* bool required */ 4:
                    message.required = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PropertyDeclaration, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.ValueKind type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        /* string default_literal = 3; */
        if (message.defaultLiteral !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.defaultLiteral);
        /* bool required = 4; */
        if (message.required !== false)
            writer.tag(4, WireType.Varint).bool(message.required);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.PropertyDeclaration
 */
export const PropertyDeclaration = new PropertyDeclaration$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ControlSchema$Type extends MessageType<ControlSchema> {
    constructor() {
        super("gooey.control.v1.ControlSchema", [
            { no: 1, name: "control", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "properties", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => PropertyDeclaration }
        ]);
    }
    create(value?: PartialMessage<ControlSchema>): ControlSchema {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.control = "";
        message.properties = [];
        if (value !== undefined)
            reflectionMergePartial<ControlSchema>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ControlSchema): ControlSchema {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string control */ 1:
                    message.control = reader.string();
                    break;
                case /* repeated gooey.control.v1.PropertyDeclaration properties */ 2:
                    message.properties.push(PropertyDeclaration.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ControlSchema, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string control = 1; */
        if (message.control !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.control);
        /* repeated gooey.control.v1.PropertyDeclaration properties = 2; */
        for (let i = 0; i < message.properties.length; i++)
            PropertyDeclaration.internalBinaryWrite(message.properties[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ControlSchema
 */
export const ControlSchema = new ControlSchema$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyRegistration$Type extends MessageType<PropertyRegistration> {
    constructor() {
        super("gooey.control.v1.PropertyRegistration", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "kind", kind: "enum", T: () => ["gooey.control.v1.ValueKind", ValueKind, "VALUE_KIND_"] },
            { no: 3, name: "initial", kind: "message", T: () => TypedValue }
        ]);
    }
    create(value?: PartialMessage<PropertyRegistration>): PropertyRegistration {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.kind = 0;
        if (value !== undefined)
            reflectionMergePartial<PropertyRegistration>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PropertyRegistration): PropertyRegistration {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.ValueKind kind */ 2:
                    message.kind = reader.int32();
                    break;
                case /* gooey.control.v1.TypedValue initial */ 3:
                    message.initial = TypedValue.internalBinaryRead(reader, reader.uint32(), options, message.initial);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PropertyRegistration, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.ValueKind kind = 2; */
        if (message.kind !== 0)
            writer.tag(2, WireType.Varint).int32(message.kind);
        /* gooey.control.v1.TypedValue initial = 3; */
        if (message.initial)
            TypedValue.internalBinaryWrite(message.initial, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.PropertyRegistration
 */
export const PropertyRegistration = new PropertyRegistration$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValueInfo$Type extends MessageType<ValueInfo> {
    constructor() {
        super("gooey.control.v1.ValueInfo", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "kind", kind: "enum", T: () => ["gooey.control.v1.EntryKind", EntryKind, "ENTRY_KIND_"] },
            { no: 3, name: "type", kind: "enum", T: () => ["gooey.control.v1.ValueKind", ValueKind, "VALUE_KIND_"] },
            { no: 4, name: "value", kind: "message", T: () => TypedValue },
            { no: 5, name: "go_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ValueInfo>): ValueInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.kind = 0;
        message.type = 0;
        message.goType = "";
        if (value !== undefined)
            reflectionMergePartial<ValueInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValueInfo): ValueInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.EntryKind kind */ 2:
                    message.kind = reader.int32();
                    break;
                case /* gooey.control.v1.ValueKind type */ 3:
                    message.type = reader.int32();
                    break;
                case /* gooey.control.v1.TypedValue value */ 4:
                    message.value = TypedValue.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                case /* string go_type */ 5:
                    message.goType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValueInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.EntryKind kind = 2; */
        if (message.kind !== 0)
            writer.tag(2, WireType.Varint).int32(message.kind);
        /* gooey.control.v1.ValueKind type = 3; */
        if (message.type !== 0)
            writer.tag(3, WireType.Varint).int32(message.type);
        /* gooey.control.v1.TypedValue value = 4; */
        if (message.value)
            TypedValue.internalBinaryWrite(message.value, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string go_type = 5; */
        if (message.goType !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.goType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.ValueInfo
 */
export const ValueInfo = new ValueInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PropertyChange$Type extends MessageType<PropertyChange> {
    constructor() {
        super("gooey.control.v1.PropertyChange", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "value", kind: "message", T: () => TypedValue }
        ]);
    }
    create(value?: PartialMessage<PropertyChange>): PropertyChange {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        if (value !== undefined)
            reflectionMergePartial<PropertyChange>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PropertyChange): PropertyChange {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.TypedValue value */ 2:
                    message.value = TypedValue.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PropertyChange, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.TypedValue value = 2; */
        if (message.value)
            TypedValue.internalBinaryWrite(message.value, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.PropertyChange
 */
export const PropertyChange = new PropertyChange$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Rect$Type extends MessageType<Rect> {
    constructor() {
        super("gooey.control.v1.Rect", [
            { no: 1, name: "x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "y", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Rect>): Rect {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.x = 0;
        message.y = 0;
        message.width = 0;
        message.height = 0;
        if (value !== undefined)
            reflectionMergePartial<Rect>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Rect): Rect {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 x */ 1:
                    message.x = reader.int32();
                    break;
                case /* int32 y */ 2:
                    message.y = reader.int32();
                    break;
                case /* int32 width */ 3:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 4:
                    message.height = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Rect, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 x = 1; */
        if (message.x !== 0)
            writer.tag(1, WireType.Varint).int32(message.x);
        /* int32 y = 2; */
        if (message.y !== 0)
            writer.tag(2, WireType.Varint).int32(message.y);
        /* int32 width = 3; */
        if (message.width !== 0)
            writer.tag(3, WireType.Varint).int32(message.width);
        /* int32 height = 4; */
        if (message.height !== 0)
            writer.tag(4, WireType.Varint).int32(message.height);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Rect
 */
export const Rect = new Rect$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Margin$Type extends MessageType<Margin> {
    constructor() {
        super("gooey.control.v1.Margin", [
            { no: 1, name: "left", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "top", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "right", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "bottom", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Margin>): Margin {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.left = 0;
        message.top = 0;
        message.right = 0;
        message.bottom = 0;
        if (value !== undefined)
            reflectionMergePartial<Margin>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Margin): Margin {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 left */ 1:
                    message.left = reader.int32();
                    break;
                case /* int32 top */ 2:
                    message.top = reader.int32();
                    break;
                case /* int32 right */ 3:
                    message.right = reader.int32();
                    break;
                case /* int32 bottom */ 4:
                    message.bottom = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Margin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 left = 1; */
        if (message.left !== 0)
            writer.tag(1, WireType.Varint).int32(message.left);
        /* int32 top = 2; */
        if (message.top !== 0)
            writer.tag(2, WireType.Varint).int32(message.top);
        /* int32 right = 3; */
        if (message.right !== 0)
            writer.tag(3, WireType.Varint).int32(message.right);
        /* int32 bottom = 4; */
        if (message.bottom !== 0)
            writer.tag(4, WireType.Varint).int32(message.bottom);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Margin
 */
export const Margin = new Margin$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Layout$Type extends MessageType<Layout> {
    constructor() {
        super("gooey.control.v1.Layout", [
            { no: 1, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "margin", kind: "message", T: () => Margin },
            { no: 4, name: "h_align", kind: "enum", T: () => ["gooey.control.v1.Align", Align, "ALIGN_"] },
            { no: 5, name: "v_align", kind: "enum", T: () => ["gooey.control.v1.Align", Align, "ALIGN_"] },
            { no: 6, name: "visibility", kind: "enum", T: () => ["gooey.control.v1.Visibility", Visibility, "VISIBILITY_"] },
            { no: 7, name: "grid_row", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "grid_col", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "grid_row_span", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "grid_col_span", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "canvas_left", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "canvas_top", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<Layout>): Layout {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.width = 0;
        message.height = 0;
        message.hAlign = 0;
        message.vAlign = 0;
        message.visibility = 0;
        message.gridRow = 0;
        message.gridCol = 0;
        message.gridRowSpan = 0;
        message.gridColSpan = 0;
        message.canvasLeft = 0;
        message.canvasTop = 0;
        if (value !== undefined)
            reflectionMergePartial<Layout>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Layout): Layout {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 width */ 1:
                    message.width = reader.int32();
                    break;
                case /* int32 height */ 2:
                    message.height = reader.int32();
                    break;
                case /* gooey.control.v1.Margin margin */ 3:
                    message.margin = Margin.internalBinaryRead(reader, reader.uint32(), options, message.margin);
                    break;
                case /* gooey.control.v1.Align h_align */ 4:
                    message.hAlign = reader.int32();
                    break;
                case /* gooey.control.v1.Align v_align */ 5:
                    message.vAlign = reader.int32();
                    break;
                case /* gooey.control.v1.Visibility visibility */ 6:
                    message.visibility = reader.int32();
                    break;
                case /* int32 grid_row */ 7:
                    message.gridRow = reader.int32();
                    break;
                case /* int32 grid_col */ 8:
                    message.gridCol = reader.int32();
                    break;
                case /* int32 grid_row_span */ 9:
                    message.gridRowSpan = reader.int32();
                    break;
                case /* int32 grid_col_span */ 10:
                    message.gridColSpan = reader.int32();
                    break;
                case /* int32 canvas_left */ 11:
                    message.canvasLeft = reader.int32();
                    break;
                case /* int32 canvas_top */ 12:
                    message.canvasTop = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Layout, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 width = 1; */
        if (message.width !== 0)
            writer.tag(1, WireType.Varint).int32(message.width);
        /* int32 height = 2; */
        if (message.height !== 0)
            writer.tag(2, WireType.Varint).int32(message.height);
        /* gooey.control.v1.Margin margin = 3; */
        if (message.margin)
            Margin.internalBinaryWrite(message.margin, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.Align h_align = 4; */
        if (message.hAlign !== 0)
            writer.tag(4, WireType.Varint).int32(message.hAlign);
        /* gooey.control.v1.Align v_align = 5; */
        if (message.vAlign !== 0)
            writer.tag(5, WireType.Varint).int32(message.vAlign);
        /* gooey.control.v1.Visibility visibility = 6; */
        if (message.visibility !== 0)
            writer.tag(6, WireType.Varint).int32(message.visibility);
        /* int32 grid_row = 7; */
        if (message.gridRow !== 0)
            writer.tag(7, WireType.Varint).int32(message.gridRow);
        /* int32 grid_col = 8; */
        if (message.gridCol !== 0)
            writer.tag(8, WireType.Varint).int32(message.gridCol);
        /* int32 grid_row_span = 9; */
        if (message.gridRowSpan !== 0)
            writer.tag(9, WireType.Varint).int32(message.gridRowSpan);
        /* int32 grid_col_span = 10; */
        if (message.gridColSpan !== 0)
            writer.tag(10, WireType.Varint).int32(message.gridColSpan);
        /* int32 canvas_left = 11; */
        if (message.canvasLeft !== 0)
            writer.tag(11, WireType.Varint).int32(message.canvasLeft);
        /* int32 canvas_top = 12; */
        if (message.canvasTop !== 0)
            writer.tag(12, WireType.Varint).int32(message.canvasTop);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.Layout
 */
export const Layout = new Layout$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TreeNode$Type extends MessageType<TreeNode> {
    constructor() {
        super("gooey.control.v1.TreeNode", [
            { no: 1, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "bounds", kind: "message", T: () => Rect },
            { no: 4, name: "layout", kind: "message", T: () => Layout },
            { no: 5, name: "focusable", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "focused", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "hovered", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "props", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "message", T: () => TypedValue } },
            { no: 9, name: "attached", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TreeNode },
            { no: 10, name: "children", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TreeNode },
            { no: 11, name: "children_elided", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 16, name: "declared", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DeclaredValue },
            { no: 17, name: "control", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TreeNode>): TreeNode {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = "";
        message.name = "";
        message.focusable = false;
        message.focused = false;
        message.hovered = false;
        message.props = {};
        message.attached = [];
        message.children = [];
        message.childrenElided = 0;
        message.declared = [];
        message.control = "";
        if (value !== undefined)
            reflectionMergePartial<TreeNode>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TreeNode): TreeNode {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string type */ 1:
                    message.type = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.Rect bounds */ 3:
                    message.bounds = Rect.internalBinaryRead(reader, reader.uint32(), options, message.bounds);
                    break;
                case /* gooey.control.v1.Layout layout */ 4:
                    message.layout = Layout.internalBinaryRead(reader, reader.uint32(), options, message.layout);
                    break;
                case /* bool focusable */ 5:
                    message.focusable = reader.bool();
                    break;
                case /* bool focused */ 6:
                    message.focused = reader.bool();
                    break;
                case /* bool hovered */ 7:
                    message.hovered = reader.bool();
                    break;
                case /* map<string, gooey.control.v1.TypedValue> props */ 8:
                    this.binaryReadMap8(message.props, reader, options);
                    break;
                case /* repeated gooey.control.v1.TreeNode attached */ 9:
                    message.attached.push(TreeNode.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated gooey.control.v1.TreeNode children */ 10:
                    message.children.push(TreeNode.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 children_elided */ 11:
                    message.childrenElided = reader.int32();
                    break;
                case /* repeated gooey.control.v1.DeclaredValue declared */ 16:
                    message.declared.push(DeclaredValue.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string control */ 17:
                    message.control = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap8(map: TreeNode["props"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof TreeNode["props"] | undefined, val: TreeNode["props"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = TypedValue.internalBinaryRead(reader, reader.uint32(), options);
                    break;
                default: throw new globalThis.Error("unknown map entry field for gooey.control.v1.TreeNode.props");
            }
        }
        map[key ?? ""] = val ?? TypedValue.create();
    }
    internalBinaryWrite(message: TreeNode, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string type = 1; */
        if (message.type !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.type);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.Rect bounds = 3; */
        if (message.bounds)
            Rect.internalBinaryWrite(message.bounds, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.Layout layout = 4; */
        if (message.layout)
            Layout.internalBinaryWrite(message.layout, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* bool focusable = 5; */
        if (message.focusable !== false)
            writer.tag(5, WireType.Varint).bool(message.focusable);
        /* bool focused = 6; */
        if (message.focused !== false)
            writer.tag(6, WireType.Varint).bool(message.focused);
        /* bool hovered = 7; */
        if (message.hovered !== false)
            writer.tag(7, WireType.Varint).bool(message.hovered);
        /* map<string, gooey.control.v1.TypedValue> props = 8; */
        for (let k of globalThis.Object.keys(message.props)) {
            writer.tag(8, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k);
            writer.tag(2, WireType.LengthDelimited).fork();
            TypedValue.internalBinaryWrite(message.props[k], writer, options);
            writer.join().join();
        }
        /* repeated gooey.control.v1.TreeNode attached = 9; */
        for (let i = 0; i < message.attached.length; i++)
            TreeNode.internalBinaryWrite(message.attached[i], writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* repeated gooey.control.v1.TreeNode children = 10; */
        for (let i = 0; i < message.children.length; i++)
            TreeNode.internalBinaryWrite(message.children[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* int32 children_elided = 11; */
        if (message.childrenElided !== 0)
            writer.tag(11, WireType.Varint).int32(message.childrenElided);
        /* repeated gooey.control.v1.DeclaredValue declared = 16; */
        for (let i = 0; i < message.declared.length; i++)
            DeclaredValue.internalBinaryWrite(message.declared[i], writer.tag(16, WireType.LengthDelimited).fork(), options).join();
        /* string control = 17; */
        if (message.control !== "")
            writer.tag(17, WireType.LengthDelimited).string(message.control);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.TreeNode
 */
export const TreeNode = new TreeNode$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeclaredValue$Type extends MessageType<DeclaredValue> {
    constructor() {
        super("gooey.control.v1.DeclaredValue", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "enum", T: () => ["gooey.control.v1.ValueKind", ValueKind, "VALUE_KIND_"] },
            { no: 3, name: "value", kind: "message", T: () => TypedValue },
            { no: 4, name: "go_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeclaredValue>): DeclaredValue {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.type = 0;
        message.goType = "";
        if (value !== undefined)
            reflectionMergePartial<DeclaredValue>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeclaredValue): DeclaredValue {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.ValueKind type */ 2:
                    message.type = reader.int32();
                    break;
                case /* gooey.control.v1.TypedValue value */ 3:
                    message.value = TypedValue.internalBinaryRead(reader, reader.uint32(), options, message.value);
                    break;
                case /* string go_type */ 4:
                    message.goType = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeclaredValue, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.ValueKind type = 2; */
        if (message.type !== 0)
            writer.tag(2, WireType.Varint).int32(message.type);
        /* gooey.control.v1.TypedValue value = 3; */
        if (message.value)
            TypedValue.internalBinaryWrite(message.value, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string go_type = 4; */
        if (message.goType !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.goType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.DeclaredValue
 */
export const DeclaredValue = new DeclaredValue$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StyleInfo$Type extends MessageType<StyleInfo> {
    constructor() {
        super("gooey.control.v1.StyleInfo", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "fg", kind: "message", T: () => Color },
            { no: 3, name: "bg", kind: "message", T: () => Color },
            { no: 4, name: "bold", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "dim", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "underline", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "reverse", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<StyleInfo>): StyleInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.bold = false;
        message.dim = false;
        message.underline = false;
        message.reverse = false;
        if (value !== undefined)
            reflectionMergePartial<StyleInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StyleInfo): StyleInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* gooey.control.v1.Color fg */ 2:
                    message.fg = Color.internalBinaryRead(reader, reader.uint32(), options, message.fg);
                    break;
                case /* gooey.control.v1.Color bg */ 3:
                    message.bg = Color.internalBinaryRead(reader, reader.uint32(), options, message.bg);
                    break;
                case /* bool bold */ 4:
                    message.bold = reader.bool();
                    break;
                case /* bool dim */ 5:
                    message.dim = reader.bool();
                    break;
                case /* bool underline */ 6:
                    message.underline = reader.bool();
                    break;
                case /* bool reverse */ 7:
                    message.reverse = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StyleInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* gooey.control.v1.Color fg = 2; */
        if (message.fg)
            Color.internalBinaryWrite(message.fg, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.Color bg = 3; */
        if (message.bg)
            Color.internalBinaryWrite(message.bg, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* bool bold = 4; */
        if (message.bold !== false)
            writer.tag(4, WireType.Varint).bool(message.bold);
        /* bool dim = 5; */
        if (message.dim !== false)
            writer.tag(5, WireType.Varint).bool(message.dim);
        /* bool underline = 6; */
        if (message.underline !== false)
            writer.tag(6, WireType.Varint).bool(message.underline);
        /* bool reverse = 7; */
        if (message.reverse !== false)
            writer.tag(7, WireType.Varint).bool(message.reverse);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.StyleInfo
 */
export const StyleInfo = new StyleInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PointerEvent$Type extends MessageType<PointerEvent> {
    constructor() {
        super("gooey.control.v1.PointerEvent", [
            { no: 1, name: "kind", kind: "enum", T: () => ["gooey.control.v1.PointerKind", PointerKind, "POINTER_KIND_"] },
            { no: 2, name: "x", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "y", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "button", kind: "enum", T: () => ["gooey.control.v1.MouseButton", MouseButton, "MOUSE_BUTTON_"] }
        ]);
    }
    create(value?: PartialMessage<PointerEvent>): PointerEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.kind = 0;
        message.x = 0;
        message.y = 0;
        message.button = 0;
        if (value !== undefined)
            reflectionMergePartial<PointerEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PointerEvent): PointerEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.PointerKind kind */ 1:
                    message.kind = reader.int32();
                    break;
                case /* int32 x */ 2:
                    message.x = reader.int32();
                    break;
                case /* int32 y */ 3:
                    message.y = reader.int32();
                    break;
                case /* gooey.control.v1.MouseButton button */ 4:
                    message.button = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PointerEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.PointerKind kind = 1; */
        if (message.kind !== 0)
            writer.tag(1, WireType.Varint).int32(message.kind);
        /* int32 x = 2; */
        if (message.x !== 0)
            writer.tag(2, WireType.Varint).int32(message.x);
        /* int32 y = 3; */
        if (message.y !== 0)
            writer.tag(3, WireType.Varint).int32(message.y);
        /* gooey.control.v1.MouseButton button = 4; */
        if (message.button !== 0)
            writer.tag(4, WireType.Varint).int32(message.button);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.PointerEvent
 */
export const PointerEvent = new PointerEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class KeyEvent$Type extends MessageType<KeyEvent> {
    constructor() {
        super("gooey.control.v1.KeyEvent", [
            { no: 1, name: "gesture", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<KeyEvent>): KeyEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.gesture = "";
        if (value !== undefined)
            reflectionMergePartial<KeyEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: KeyEvent): KeyEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string gesture */ 1:
                    message.gesture = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: KeyEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string gesture = 1; */
        if (message.gesture !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.gesture);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.KeyEvent
 */
export const KeyEvent = new KeyEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InputEvent$Type extends MessageType<InputEvent> {
    constructor() {
        super("gooey.control.v1.InputEvent", [
            { no: 1, name: "key", kind: "message", oneof: "event", T: () => KeyEvent },
            { no: 2, name: "pointer", kind: "message", oneof: "event", T: () => PointerEvent }
        ]);
    }
    create(value?: PartialMessage<InputEvent>): InputEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.event = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<InputEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InputEvent): InputEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* gooey.control.v1.KeyEvent key */ 1:
                    message.event = {
                        oneofKind: "key",
                        key: KeyEvent.internalBinaryRead(reader, reader.uint32(), options, (message.event as any).key)
                    };
                    break;
                case /* gooey.control.v1.PointerEvent pointer */ 2:
                    message.event = {
                        oneofKind: "pointer",
                        pointer: PointerEvent.internalBinaryRead(reader, reader.uint32(), options, (message.event as any).pointer)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InputEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* gooey.control.v1.KeyEvent key = 1; */
        if (message.event.oneofKind === "key")
            KeyEvent.internalBinaryWrite(message.event.key, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* gooey.control.v1.PointerEvent pointer = 2; */
        if (message.event.oneofKind === "pointer")
            PointerEvent.internalBinaryWrite(message.event.pointer, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message gooey.control.v1.InputEvent
 */
export const InputEvent = new InputEvent$Type();
