# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gooey.control.v1 import control_pb2 as gooey_dot_control_dot_v1_dot_control__pb2


class ControlServiceStub:
    """ControlService is the request/response surface of a running gooey
    app. The MCP tools (issue #112) are a thin adapter over exactly
    these RPCs; nothing an MCP tool can do is absent here, and nothing
    here needs MCP.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SnapshotTree = channel.unary_unary(
                '/gooey.control.v1.ControlService/SnapshotTree',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SnapshotTreeRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SnapshotTreeResponse.FromString,
                _registered_method=True)
        self.ScreenText = channel.unary_unary(
                '/gooey.control.v1.ControlService/ScreenText',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ScreenTextRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ScreenTextResponse.FromString,
                _registered_method=True)
        self.ListValues = channel.unary_unary(
                '/gooey.control.v1.ControlService/ListValues',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ListValuesRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ListValuesResponse.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/gooey.control.v1.ControlService/GetProperty',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.GetPropertyRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.GetPropertyResponse.FromString,
                _registered_method=True)
        self.SetProperty = channel.unary_unary(
                '/gooey.control.v1.ControlService/SetProperty',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SetPropertyRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SetPropertyResponse.FromString,
                _registered_method=True)
        self.InvokeCommand = channel.unary_unary(
                '/gooey.control.v1.ControlService/InvokeCommand',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.InvokeCommandRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.InvokeCommandResponse.FromString,
                _registered_method=True)
        self.SendKeys = channel.unary_unary(
                '/gooey.control.v1.ControlService/SendKeys',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SendKeysRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SendKeysResponse.FromString,
                _registered_method=True)
        self.SendPointer = channel.unary_unary(
                '/gooey.control.v1.ControlService/SendPointer',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SendPointerRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SendPointerResponse.FromString,
                _registered_method=True)
        self.SetFocus = channel.unary_unary(
                '/gooey.control.v1.ControlService/SetFocus',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SetFocusRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SetFocusResponse.FromString,
                _registered_method=True)
        self.SwapMarkup = channel.unary_unary(
                '/gooey.control.v1.ControlService/SwapMarkup',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SwapMarkupRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SwapMarkupResponse.FromString,
                _registered_method=True)
        self.RegisterProperties = channel.unary_unary(
                '/gooey.control.v1.ControlService/RegisterProperties',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.RegisterPropertiesRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.RegisterPropertiesResponse.FromString,
                _registered_method=True)
        self.GetDeclaredSchema = channel.unary_unary(
                '/gooey.control.v1.ControlService/GetDeclaredSchema',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.GetDeclaredSchemaRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.GetDeclaredSchemaResponse.FromString,
                _registered_method=True)
        self.PatchMarkup = channel.unary_unary(
                '/gooey.control.v1.ControlService/PatchMarkup',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.PatchMarkupRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.PatchMarkupResponse.FromString,
                _registered_method=True)
        self.ListStyles = channel.unary_unary(
                '/gooey.control.v1.ControlService/ListStyles',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ListStylesRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ListStylesResponse.FromString,
                _registered_method=True)
        self.ValidateMarkup = channel.unary_unary(
                '/gooey.control.v1.ControlService/ValidateMarkup',
                request_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ValidateMarkupRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ValidateMarkupResponse.FromString,
                _registered_method=True)


class ControlServiceServicer:
    """ControlService is the request/response surface of a running gooey
    app. The MCP tools (issue #112) are a thin adapter over exactly
    these RPCs; nothing an MCP tool can do is absent here, and nothing
    here needs MCP.
    """

    def SnapshotTree(self, request, context):
        """SnapshotTree serializes the live component tree — MCP tree_snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScreenText(self, request, context):
        """ScreenText reads the retained cell plane as of the last composed
        frame — MCP screen_text. Never composes a frame of its own: doing
        so would mark dirty nodes clean and steal the app's damage counts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListValues(self, request, context):
        """ListValues describes the bindable surface — MCP list_values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """GetProperty reads one named property. New surface (MCP reads via
        list_values); the natural unary read half of SetProperty.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProperty(self, request, context):
        """SetProperty writes one named source property — MCP set_value. The
        TypedValue's case must match the handle's type; a mismatch is
        INVALID_ARGUMENT naming both sides, and nothing changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeCommand(self, request, context):
        """InvokeCommand runs a named command — MCP invoke_command.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendKeys(self, request, context):
        """SendKeys injects key events into the app's single ordered input
        stream — MCP send_keys. Routed through the composition, not the
        app-level handler: a client cannot reach the quit key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPointer(self, request, context):
        """SendPointer injects one pointer event — MCP send_mouse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetFocus(self, request, context):
        """SetFocus moves keyboard focus to a named element — MCP focus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwapMarkup(self, request, context):
        """SwapMarkup replaces the page with new markup built against the
        app's existing binding context — MCP swap_markup. Optional
        registrations grow the viewmodel first (issue #89). Atomic: a
        failed build leaves the running tree, the name table AND the
        registrations untouched.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterProperties(self, request, context):
        """RegisterProperties materializes new typed source properties in the
        binding context without swapping markup (issue #89). A name that
        already exists is INVALID_ARGUMENT — one source of truth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeclaredSchema(self, request, context):
        """GetDeclaredSchema returns a document's <x:Property> declaration
        block as a schema (issue #62): the contract a values payload must
        satisfy before the document can build.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PatchMarkup(self, request, context):
        """PatchMarkup replaces ONE named element's subtree, leaving the rest
        of the page — and every sibling's component state — untouched (MCP
        patch_markup, issue #117). The fragment builds against the live
        binding context; its root element must carry the same Name= as the
        element it replaces (the name is the address, and the address
        survives iteration). Layout attributes the fragment does not
        restate (Grid.Row, Width, Margin, ...) are preserved from the old
        element, per attribute. Atomic: any failure — bad markup, wrong
        root name, a name colliding with a surviving element, a parent
        container the server cannot rewrite — is INVALID_ARGUMENT (or
        NOT_FOUND for an unknown address) and the running tree, name table
        and focus are exactly as they were.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStyles(self, request, context):
        """ListStyles reports the markup context's style table — the names a
        Style="..." attribute can resolve (MCP list_styles, issue #117). An
        unknown style silently renders unstyled, so a markup generator must
        draw from this list.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateMarkup(self, request, context):
        """ValidateMarkup checks a document against the live binding context —
        the exact parse-and-bind path SwapMarkup runs, including declared
        properties — without attaching anything or composing a frame (MCP
        validate_markup, issue #117). INVALID markup is a normal response
        carrying the typed load error, NOT a status error: the RPC was
        asked whether the markup is valid and it answered, which is what
        lets a generation loop retry cheaply without flickering the page.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SnapshotTree': grpc.unary_unary_rpc_method_handler(
                    servicer.SnapshotTree,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SnapshotTreeRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SnapshotTreeResponse.SerializeToString,
            ),
            'ScreenText': grpc.unary_unary_rpc_method_handler(
                    servicer.ScreenText,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ScreenTextRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ScreenTextResponse.SerializeToString,
            ),
            'ListValues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListValues,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ListValuesRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ListValuesResponse.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.GetPropertyRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.GetPropertyResponse.SerializeToString,
            ),
            'SetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProperty,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SetPropertyRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SetPropertyResponse.SerializeToString,
            ),
            'InvokeCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeCommand,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.InvokeCommandRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.InvokeCommandResponse.SerializeToString,
            ),
            'SendKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.SendKeys,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SendKeysRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SendKeysResponse.SerializeToString,
            ),
            'SendPointer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPointer,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SendPointerRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SendPointerResponse.SerializeToString,
            ),
            'SetFocus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetFocus,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SetFocusRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SetFocusResponse.SerializeToString,
            ),
            'SwapMarkup': grpc.unary_unary_rpc_method_handler(
                    servicer.SwapMarkup,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.SwapMarkupRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.SwapMarkupResponse.SerializeToString,
            ),
            'RegisterProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterProperties,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.RegisterPropertiesRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.RegisterPropertiesResponse.SerializeToString,
            ),
            'GetDeclaredSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeclaredSchema,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.GetDeclaredSchemaRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.GetDeclaredSchemaResponse.SerializeToString,
            ),
            'PatchMarkup': grpc.unary_unary_rpc_method_handler(
                    servicer.PatchMarkup,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.PatchMarkupRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.PatchMarkupResponse.SerializeToString,
            ),
            'ListStyles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStyles,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ListStylesRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ListStylesResponse.SerializeToString,
            ),
            'ValidateMarkup': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateMarkup,
                    request_deserializer=gooey_dot_control_dot_v1_dot_control__pb2.ValidateMarkupRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_control__pb2.ValidateMarkupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gooey.control.v1.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gooey.control.v1.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService:
    """ControlService is the request/response surface of a running gooey
    app. The MCP tools (issue #112) are a thin adapter over exactly
    these RPCs; nothing an MCP tool can do is absent here, and nothing
    here needs MCP.
    """

    @staticmethod
    def SnapshotTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/SnapshotTree',
            gooey_dot_control_dot_v1_dot_control__pb2.SnapshotTreeRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.SnapshotTreeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScreenText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/ScreenText',
            gooey_dot_control_dot_v1_dot_control__pb2.ScreenTextRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.ScreenTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/ListValues',
            gooey_dot_control_dot_v1_dot_control__pb2.ListValuesRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.ListValuesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/GetProperty',
            gooey_dot_control_dot_v1_dot_control__pb2.GetPropertyRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.GetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/SetProperty',
            gooey_dot_control_dot_v1_dot_control__pb2.SetPropertyRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.SetPropertyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/InvokeCommand',
            gooey_dot_control_dot_v1_dot_control__pb2.InvokeCommandRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.InvokeCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/SendKeys',
            gooey_dot_control_dot_v1_dot_control__pb2.SendKeysRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.SendKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPointer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/SendPointer',
            gooey_dot_control_dot_v1_dot_control__pb2.SendPointerRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.SendPointerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetFocus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/SetFocus',
            gooey_dot_control_dot_v1_dot_control__pb2.SetFocusRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.SetFocusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwapMarkup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/SwapMarkup',
            gooey_dot_control_dot_v1_dot_control__pb2.SwapMarkupRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.SwapMarkupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/RegisterProperties',
            gooey_dot_control_dot_v1_dot_control__pb2.RegisterPropertiesRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.RegisterPropertiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeclaredSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/GetDeclaredSchema',
            gooey_dot_control_dot_v1_dot_control__pb2.GetDeclaredSchemaRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.GetDeclaredSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PatchMarkup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/PatchMarkup',
            gooey_dot_control_dot_v1_dot_control__pb2.PatchMarkupRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.PatchMarkupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStyles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/ListStyles',
            gooey_dot_control_dot_v1_dot_control__pb2.ListStylesRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.ListStylesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateMarkup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gooey.control.v1.ControlService/ValidateMarkup',
            gooey_dot_control_dot_v1_dot_control__pb2.ValidateMarkupRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_control__pb2.ValidateMarkupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
