# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gooey.control.v1 import session_pb2 as gooey_dot_control_dot_v1_dot_session__pb2


class SessionServiceStub:
    """SessionService attaches a client to a running app for the lifetime
    of the stream. Push replaces polling (issue #49): a subscribed
    client hears about a change when the frame containing it composes,
    not on the next 400ms tick.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Attach = channel.stream_stream(
                '/gooey.control.v1.SessionService/Attach',
                request_serializer=gooey_dot_control_dot_v1_dot_session__pb2.AttachRequest.SerializeToString,
                response_deserializer=gooey_dot_control_dot_v1_dot_session__pb2.AttachResponse.FromString,
                _registered_method=True)


class SessionServiceServicer:
    """SessionService attaches a client to a running app for the lifetime
    of the stream. Push replaces polling (issue #49): a subscribed
    client hears about a change when the frame containing it composes,
    not on the next 400ms tick.
    """

    def Attach(self, request_iterator, context):
        """Attach opens a session. The first client message must be
        `subscribe`; every later one is an `act`. Server messages start
        with `welcome` and then interleave act results with subscribed
        events. Closing either direction ends the session; the app
        outlives every session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Attach': grpc.stream_stream_rpc_method_handler(
                    servicer.Attach,
                    request_deserializer=gooey_dot_control_dot_v1_dot_session__pb2.AttachRequest.FromString,
                    response_serializer=gooey_dot_control_dot_v1_dot_session__pb2.AttachResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gooey.control.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gooey.control.v1.SessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SessionService:
    """SessionService attaches a client to a running app for the lifetime
    of the stream. Push replaces polling (issue #49): a subscribed
    client hears about a change when the frame containing it composes,
    not on the next 400ms tick.
    """

    @staticmethod
    def Attach(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gooey.control.v1.SessionService/Attach',
            gooey_dot_control_dot_v1_dot_session__pb2.AttachRequest.SerializeToString,
            gooey_dot_control_dot_v1_dot_session__pb2.AttachResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
